// 23/05/2022
var Dictionary =
{
    "Añadir": "Añadir",
    "Avatar": "Avatar",
    "BAR_Popup_NoElements": "No hay elementos",
    "Billing": "Facturación",
    "Billing_AddLine": "Añadir línea",
    "Billing_AutoGenerate": "Generación facturas",
    "Billing_AutoGenerate_Error_NoMonth": "Se ha de indicar el mes",
    "Billing_AutoGenerate_Error_NoYear": "Se ha de indicar el año",
    "Billing_AutoGenerateWorking": "Generando facturas",
    "Billing_Categories": "Categorias",
    "Billing_Category_Btn_Add": "Añadir categoria",
    "Billing_Category_Description": "Categoria",
    "Billing_Category_Label_Description": "Nombre",
    "Billing_Category_List": "Listado de categorias",
    "Billing_Category_Title_Add": "Añadir categoria",
    "Billing_Category_Title_Edit": "Editar categoria",
    "Billing_Concept": "Concepto",
    "Billing_Concept_Btn_Add": "Añadir concepto",
    "Billing_Concept_FixedPrice": "A precio por unidad",
    "Billing_Concept_FreePrice": "Importe libre",
    "Billing_Concept_IVA": "IVA",
    "Billing_Concept_Label_Amount": "Import base",
    "Billing_Concept_Label_CategoryId": "Categoria",
    "Billing_Concept_Label_Description": "Descripción",
    "Billing_Concept_Label_IVA": "IVA",
    "Billing_Concept_List": "Listado de conceptos",
    "Billing_Concept_Name": "Concepto",
    "Billing_Concept_PDF_Header_Category": "Categoria",
    "Billing_Concept_PDF_Header_Concept": "Concepto",
    "Billing_Concept_PDF_Header_PVP": "P.V.P.",
    "Billing_Concept_PDF_Title": "Preucios de conceptos",
    "Billing_Concept_Price": "Precio",
    "Billing_Concept_PVP": "PVP",
    "Billing_Concept_Title_Add": "Añadir concepto",
    "Billing_Concept_Title_Edit": "Editar concepto",
    "Billing_ConceptCategory": "Categoria",
    "Billing_ConceptList": "Listado de conceptos",
    "Billing_Concepts": "Conceptos",
    "Billing_ErrorMessage_NoLines": "No se puede confirmar la factura sin líneas",
    "Billing_Header_BaseAmount": "Base Imp.",
    "Billing_Header_Date": "Fecha",
    "Billing_Header_Number": "#",
    "Billing_Header_Payer": "Pagador",
    "Billing_Header_Status": "Estado",
    "Billing_Header_Subject": "Descripción",
    "Billing_Header_Total": "Total",
    "Billing_Header_TotalIVA": "IVA",
    "Billing_Invoice": "Factura",
    "Billing_Invoice_ErrorCrossDates": "La fecha de vencimiento no puede ser anterior a la fecha de la factura",
    "Billing_Invoice_ErrorCustomerRequired": "El cliente es obligatorio",
    "Billing_Invoice_ErrorDateMalformed": "La fecha de factura no es válida",
    "Billing_Invoice_ErrorDateRequired": "La fecha de factura es obliatoria",
    "Billing_Invoice_ErrorDateVtoMalformed": "La fecha de vencimiento no es válida",
    "Billing_Invoice_ErrorDateVtoRequired": "La fecha de vencimiento es obliatoria",
    "Billing_Invoice_ErrorPaymentMethodRequired": "La forma de pago es obliatoria",
    "Billing_Invoice_FooterCurrency": "Precios expresados en euros",
    "Billing_Invoice_Label_Date": "Fecha",
    "Billing_Invoice_Label_DateVto": "Fecha vencimiento",
    "Billing_Invoice_Label_TotalBaseImponible": "Total base imponible",
    "Billing_Invoice_Label_TotalFacturaPDF": "Total factura",
    "Billing_Invoice_Label_TotalIVA": "Total IVA",
    "Billing_Invoice_Message_Creating": "Creando factura",
    "Billing_Invoice_Status_0": "Proforma",
    "Billing_Invoice_Status_1": "Confirmada",
    "Billing_Invoice_Status_2": "Enviada",
    "Billing_Invoice_Status_3": "Cobrada",
    "Billing_Invoice_Status_4": "Devueltas",
    "Billing_Invoice_Status_5": "Anulada",
    "Billing_Invoice_Title_InvoiceData": "Datos factura",
    "Billing_InvoiceLine_Title_Delete": "Eliminar línea",
    "Billing_InvoiceLine_Title_Edit": "Editar línea",
    "Billing_InvoiceNew": "Nueva factura",
    "Billing_Invoices": "Facturas",
    "Billing_IVA_1": "Exento",
    "Billing_IVA_2": "Super reducido 4%",
    "Billing_IVA_3": "Reducido 10%",
    "Billing_IVA_4": "General 21%",
    "Billing_Label_BankAccount": "Cuenta bancaria",
    "Billing_Label_Customer": "Cliente",
    "Billing_Label_Date": "Fecha",
    "Billing_Label_DateVto": "Fecha vencimiento",
    "Billing_Label_InvoicesCount": "Número de facturas",
    "Billing_Label_PaymentMethod": "Forma de pago",
    "Billing_List": "Listado de facturas",
    "Billing_MassBtn": "Acciones en bloque",
    "Billing_MassBtn_Confirm": "Confirmar proformas",
    "Billing_MassBtn_CreateSEPA": "Crear SEPA",
    "Billing_MassBtn_Delete": "Eliminar proformas",
    "Billing_MassBtn_MailSend": "Enviar por mail",
    "Billing_MassBtn_MarkAsRefused": "Marcar como devueltas",
    "Billing_MassBtn_Print": "Imprimir",
    "Billing_MassBtn_SendMail": "Enviar por e-mail",
    "Billing_MassBtn_SepaPreview": "Previsualizar SEPA",
    "Billing_MassTitle": "Acciones disponibles",
    "Billing_Message_Confirm": "La factura será confirmada y no se podrá modificar",
    "Billing_Message_ConfirmingInvoice": "Confirmando proforma",
    "Billing_Message_PrintProforma": "Imprimiendo proforma",
    "Billing_NumFacturaPDF": "Factura nº",
    "Billing_PaymentMethod_0": "Efectivo",
    "Billing_PaymentMethod_1": "Tranferencia bancaria",
    "Billing_PaymentMethod_2": "Tarjeta bancaria",
    "Billing_PaymentMethod_3": "Domiciliación bancaria",
    "Billing_Receipt": "Recibo",
    "Billing_Receipt_HeaderPDF_Amount": "Precio U.",
    "Billing_Receipt_HeaderPDF_Base": "Base I.",
    "Billing_Receipt_HeaderPDF_Description": "Descripción",
    "Billing_Receipt_HeaderPDF_IVA": "IVA",
    "Billing_Receipt_HeaderPDF_Quantity": "Cantidad",
    "Billing_Receipt_HeaderPDF_Total": "Total",
    "Billing_Recibos": "Ver recibos",
    "Calendar_ActualMonth": "Mes actual",
    "Calendar_NextMonth": "Próximo mes",
    "Calendar_PreviousMonth": "Mes anterior",
    "Calendar_Type_DeadLine": "Límite",
    "Calendar_Type_Event": "Evento",
    "Calendar_Type_Other": "Otro",
    "Calendar_Type_Task": "Tarea",
    "Chosen_default_multiple_text": "Seleccione opciones",
    "Chosen_default_no_result_text": "No hay resultados",
    "Chosen_default_single_text": "Selecione una opción",
    "Chosen_NoResultsText": "No hay coincidencias",
    "Common_Accept": "Aceptar",
    "Common_AcceptAndExit": "Aceptar y salir",
    "Common_Action_Success": "Operación realizada con éxito",
    "Common_Actions": "Acciones",
    "Common_Activate_Popup_BtnOk": "Activar",
    "Common_Activate_Popup_Question": "¿Desea activar",
    "Common_Activate_Popup_Title": "Activar registro",
    "Common_Activated": "Activado",
    "Common_Active": "Activo",
    "Common_Active_Plural": "Activos",
    "Common_Activity": "Actividad",
    "Common_ActualMonth": "Mes actual",
    "Common_Add": "Añadir",
    "Common_Administration": "Administración",
    "Common_Alerts": "Avisos",
    "Common_All": "Todos",
    "Common_All_Female": "Toda",
    "Common_All_Female_Plural": "Todas",
    "Common_All_Male": "Todo",
    "Common_All_Male_Plural": "Todos",
    "Common_AlreadyExists": "Ya existe",
    "Common_Attach_BtnAdd": "Añadir documento",
    "Common_Attach_BtnDownloadAll": "Descargar todo",
    "Common_Attach_TabTitle": "Documentos adjuntos",
    "Common_Back": "Volver",
    "Common_BrowserUpgrade": "Please upgrade your browser, because your current browser lacks some new features we need!",
    "Common_Btn_AddDocument": "Crear document",
    "Common_Btn_DeleteDocument": "Eliminar documento",
    "Common_Btn_DeleteDocumentHistory": "Eliminar document",
    "Common_Btn_DeleteImage": "Eliminar imagen",
    "Common_Btn_DownloadDocument": "Descargar documento",
    "Common_Btn_GoUrl": "Visitar enlace",
    "Common_Btn_HistoryDocument": "Ver historial del documento",
    "Common_Btn_SendMail": "Enviar email",
    "Common_Btn_SignDocument": "Firmar documento",
    "Common_Btn_SignedDocument": "Documento firmado",
    "Common_Btn_UploadDocument": "Subir documento",
    "Common_Btn_UploadImage": "Subir imagen",
    "Common_Btn_ViewDocument": "Ver documento",
    "Common_Btn_ViewDocumentGallery": "Ver documentos",
    "Common_Btn_ViewImage": "Ver imagen",
    "Common_Calendar_Label_Date": "Fecha",
    "Common_Calendar_Label_Location": "Lugar",
    "Common_Calendar_Label_Text": "Descripción",
    "Common_Cancel": "Cancelar",
    "Common_CanNotDelete": "No se puede eliminar",
    "Common_Change": "Cambiar",
    "Common_ChangeCompnay": "Cambiar de compañía",
    "Common_Chronometer_Hours": "horas",
    "Common_Chronometer_Minutes": "minutos",
    "Common_Chronometer_Seconds": "segundos",
    "Common_Clear": "Borrar",
    "Common_Close": "Cerrar",
    "Common_Color_Blue": "Azúl",
    "Common_Color_Green": "Verde",
    "Common_Color_Red": "Rojo",
    "Common_Color_Yellow": "Amarillo",
    "Common_Comparer_eq": "igual a",
    "Common_Comparer_eqgt": "mayor o igual que",
    "Common_Comparer_eqlt": "menor o igual que",
    "Common_Comparer_gt": "mayor que",
    "Common_Comparer_lt": "menor que",
    "Common_ComparerSign_eq": "=",
    "Common_ComparerSign_eqgt": ">=",
    "Common_ComparerSign_eqlt": "<=",
    "Common_ComparerSign_gt": ">",
    "Common_ComparerSign_lt": "<",
    "Common_Configuration": "Panel de control",
    "Common_ConnectedAs": "Conectado como",
    "Common_Connecting": "Conectando...",
    "Common_Continue": "Continuar",
    "Common_CreatedBy": "Generado por",
    "Common_Dashboard": "Visión general",
    "Common_DashboardReset": "Reestablecer original",
    "Common_Date": "Fecha",
    "Common_DateClose": "Fecha cierre",
    "Common_DateExecution": "F. prevista",
    "Common_Day": "Día",
    "Common_DayPart_Afternon": "Tarde",
    "Common_DayPart_Morning": "Mañana",
    "Common_Days": "Días",
    "Common_Delete": "Eliminar",
    "Common_Delete_Popup_BtnOk": "Eliminar",
    "Common_Delete_Popup_Question": "¿Desea eliminar",
    "Common_Delete_Popup_Title": "Eliminar registro",
    "Common_DeleteMessage": "¿Seguro que quiere eliminar",
    "Common_Dirty_Popup_Title": "Cambios sin guardar",
    "Common_DirtyTable_Header_Actual": "Valor actual",
    "Common_DirtyTable_Header_FieldName": "Dato",
    "Common_DirtyTable_Header_Original": "Valor original",
    "Common_DirtyTable_Message": "Algunos datos han cambiado y no se han guardado.",
    "Common_DocumentGallery_Header_DateTime": "Fecha",
    "Common_DocumentGallery_Header_FileName": "Documento",
    "Common_DocumentGallery_NoData": "No hay documentos",
    "Common_DocumentHistory_Header_DateTime": "Fecha",
    "Common_DocumentHistory_Header_FileName": "Documento",
    "Common_DocumentHistory_NoData": "No hay datos",
    "Common_DocumentHistory_Popup_Message": "Versiones del documento",
    "Common_DocumentHistory_Popup_Title": "Historial del documento",
    "Common_DownloadZip": "Descargar zip",
    "Common_DualListBox_Filtered": "Filtrado",
    "Common_Edit": "Editar",
    "Common_Empty": "Vacío",
    "Common_EmptyList": "Lista vacía",
    "Common_Error": "Error",
    "Common_Error_AlreadyExists": "Ya existe",
    "Common_Error_Application": "Se ha producido un error en la aplicación",
    "Common_Error_BeforeStart": "La fecha no puede ser anterior a la de inicio",
    "Common_Error_DateMalformed": "La fecha no es correcta",
    "Common_Error_EmailMalformed": "Email incorrecto",
    "Common_Error_Import_TooBig": "\"\"<strong>\"\"#\"\"</strong> Es demasiado grande\"\"",
    "Common_Error_Import_UnsupportedType": "El fichero es del tipo &quot;\"<strong>\"\"#\"\"</strong>&quot\"; que no es válido para la importación de datos.",
    "Common_Error_IncorrectMail": "El correo es incorrecto",
    "Common_Error_IncorrectPassword": "Contraseña no válida",
    "Common_Error_Kernel_Delete": "No se puede eliminar porque es parte básica de la aplicación",
    "Common_Error_Kernel_Edit": "No se puede modificar porque es parte básica de la aplicación",
    "Common_Error_LastActive": "No se puede eliminar porque es la única definida",
    "Common_Error_MaximumToday": "La fecha no puede ser posterior a hoy",
    "Common_Error_MinimumOneAction": "Escoger una opción",
    "Common_Error_MoneyMalformed": "No es un valor correcto",
    "Common_Error_NameAlreadyExists": "Ya existe",
    "Common_Error_NoAccess": "El elemento seleccionado no está disponible",
    "Common_Error_NoCalibrationsDefined": "No hay calibraciones definidas",
    "Common_Error_NoDeletable": "No se puede eliminar",
    "Common_Error_NoEditable": "No se puede modificar",
    "Common_Error_NoFileSelected": "Se ha de seleccionar un fichero",
    "Common_Error_NoGantt": "Error, no se puede crear el diagrama Gantt",
    "Common_Error_NoUploadFile": "Se ha de seleccionar un archivo",
    "Common_Error_NoVerificationsDefined": "No hay verificaciones definidas",
    "Common_Error_SelectNone": "Ha de seleccionar una opción",
    "Common_Error_UnsupportedFile": "Tipo de documento no admitido",
    "Common_Error_UrlMalformed": "Url incorrecta",
    "Common_Error_UserCanNotAccess": "El usuario no tiene permisos para acceder a la aplicación",
    "Common_ErrorMessage_CanNotDelete": "No se puede eliminar",
    "Common_ErrorMessage_InUse": "No se puede eliminar porque está en uso",
    "Common_ErrorMessage_IsSelected": "Ya está seleccionado",
    "Common_ErrorResumeIntro": "Revise los siguientes errores",
    "Common_Exit": "Salir",
    "Common_Export_CSV": "Exportar a CSV",
    "Common_Export_PDF": "Exportar a PDF",
    "Common_External": "Externo",
    "Common_FAQs_Popup_Title": "Editar FAQ",
    "Common_Favorites": "En seguimiento",
    "Common_Feature_Alert_AfterLogin_Popup_Title": "Estas tares requiere una acción inmediata",
    "Common_Feature_Geolocation_Button": "Mostrar mapa",
    "Common_Filter": "Filtrar",
    "Common_FinishDate": "Finalización",
    "Common_Follow": "Poner en seguimiento",
    "Common_Form_Errors": "Revise los datos del formulario",
    "Common_FormErrors_Title": "Revise los siguientes datos",
    "Common_From": "Desde",
    "Common_Grants_NoAccess": "Sin acceso al ítem",
    "Common_HasUserAsigned": "Usuario asignado",
    "Common_Help": "Ayuda",
    "Common_Here": "aquí",
    "Common_Home": "Inicio",
    "Common_ImageGallery_AddImage": "Añadir imagen",
    "Common_ImageGallery_Popup_Title": "Añadir imagen a la galería",
    "Common_ImageGallery_Popup_Title_ActualImage": "Seleccionar imagen",
    "Common_ImagePopup_Btn_Select": "Seleccionar imagen",
    "Common_ImagePopup_Title_ActualImage": "Actual",
    "Common_ImagePopup_Title_New": "Añadir imagen",
    "Common_ImagePopup_Title_NewImage": "Nueva imagen",
    "Common_ImagePopup_Title_Update": "Sustituir imagen",
    "Common_Import": "Importar",
    "Common_Import_AcceptData": "Aceptar datos y realizar carga",
    "Common_Import_DropFile1": "Arrastrar fichero",
    "Common_Import_DropFile2": "para importar",
    "Common_Import_DropFile3": "ó clickar",
    "Common_Import_Error_NoField": "El campo <strong>{0}</strong> no está en el fichero.",
    "Common_Import_Error_NoFKFound": "No existe <strong>{0}</strong> como {1} en el sistema.",
    "Common_Import_Error_RequiredField": "El campo <strong>{0}</strong> es obligatorio.",
    "Common_Import_ErrorHeader_Field": "Campo",
    "Common_Import_ErrorHeader_Line": "Línea",
    "Common_Import_ErrorHeader_Message": "Mensaje",
    "Common_Import_Errors": "Se han encontrado errores en el fichero",
    "Common_Import_Explanation": "Al final de la página encontrará las instrucciones para la importación.",
    "Common_Import_Go": "Realizando importación",
    "Common_Import_InstructionsTitle": "Instrucciones",
    "Common_Import_Message_ValidatingData": "Comprobando validez de datos",
    "Common_Import_ReadSuccessTitle": "Previsualización de datos a cargar",
    "Common_Import_ReloadFile": "Volver a cargar el fichero",
    "Common_Inactive": "Inactivo",
    "Common_Inactive_Plural": "Inactivos",
    "Common_Info": "Información",
    "Common_Internal": "Interno",
    "Common_Label_Days": "días",
    "Common_Label_Months": "meses",
    "Common_Label_Weeks": "semanas",
    "Common_Label_Years": "años",
    "Common_LastWeek": "Última semana",
    "Common_ListPdf": "Imprimir",
    "Common_LoadingData": "Cargando datos...",
    "Common_Logout": "Salir",
    "Common_MailLink_List_Header_Description": "Emails relacionados",
    "Common_Map_Accuracy": "Precisar",
    "Common_Map_GeolocationSaved": "Geoposición guardada",
    "Common_Map_Latitude": "Latitud",
    "Common_Map_Longitude": "Longitud",
    "Common_Map_NewLatitude": "Nueva latitud",
    "Common_Map_NewLongitude": "Nueva longitud",
    "Common_Map_NoData": "No hay definida información de geolocalización.",
    "Common_Map_Resolve": "Geoposicionar",
    "Common_Map_Suggestion": "Dirección orientativa",
    "Common_MaximumUploadSize": "Tamaño máximo superado",
    "Common_Message_Deleting": "Eliminando...",
    "Common_Message_FormErrors": "Revise los datos del formulario",
    "Common_Message_SaveItemFirst": "Antes hay que guardar los datos",
    "Common_Message_Saving": "Guardando...",
    "Common_ModifiedBy": "Modificado por",
    "Common_Modify": "Modificar",
    "Common_Month": "Mes",
    "Common_MonthName_April": "Abril",
    "Common_MonthName_August": "Agosto",
    "Common_MonthName_December": "Diciembre",
    "Common_MonthName_February": "Febrero",
    "Common_MonthName_January": "Enero",
    "Common_MonthName_July": "Julio",
    "Common_MonthName_June": "Junio",
    "Common_MonthName_March": "Marzo",
    "Common_MonthName_May": "Mayo",
    "Common_MonthName_November": "Noviembre",
    "Common_MonthName_October": "Octubre",
    "Common_MonthName_September": "Septiembre",
    "Common_MonthNameShort_April": "Abr",
    "Common_MonthNameShort_August": "Ago",
    "Common_MonthNameShort_December": "Dec",
    "Common_MonthNameShort_February": "Feb",
    "Common_MonthNameShort_January": "Gen",
    "Common_MonthNameShort_July": "Jul",
    "Common_MonthNameShort_June": "Jun",
    "Common_MonthNameShort_March": "Mar",
    "Common_MonthNameShort_May": "Mai",
    "Common_MonthNameShort_November": "Nov",
    "Common_MonthNameShort_October": "Oct",
    "Common_MonthNameShort_September": "Sep",
    "Common_Months": "Meses",
    "Common_Name": "Usuario",
    "Common_NeverConnected": "Nunca ha accedido",
    "Common_New": "Nuevo",
    "Common_Next": "Siguiente",
    "Common_No": "No",
    "Common_No_Access": "Acceso no permitido",
    "Common_No_Access_Message": "Se han registrado los siguientes datos por motivos de seguridad",
    "Common_No_Access_Title": "No tiene acceso al elemento que intenta visualizar",
    "Common_NoAlerts": "<strong>¡Felicidades!</strong><br />No hay ninguna alerta pendiente",
    "Common_NoData": "No hay datos",
    "Common_NoF12": "Sólo administradores tienen permitida esta acción",
    "Common_NoGrants": "Usuario sin permisos",
    "Common_NoGrants_Explanation": "Póngase en contacto con el administrador de la aplicación en la siguiente dirección de correo",
    "Common_None": "Ninguno",
    "Common_None_Female": "Ninguna",
    "Common_None_Male": "Ninguno",
    "Common_NoRefresh": "Use los controles de navegación de la aplicación",
    "Common_Notes": "Notas",
    "Common_NotSet_Female": "No especificada",
    "Common_NotSet_Male": "No especificado",
    "Common_NowText": "Ahora mismo",
    "Common_Other": "Otro",
    "Common_Other_Plural": "Otros",
    "Common_Period": "Periodo",
    "Common_PeriodAll": "Todo el periodo",
    "Common_Popup_ChangePassword_Error_InvalidPassword": "La contraseña actual no es válida",
    "Common_Popup_ChangePassword_Label_Actual": "Actual",
    "Common_Popup_ChangePassword_Label_Confirmation": "Confirmar",
    "Common_Popup_ChangePassword_Label_New": "Nueva",
    "Common_Popup_ChangePassword_Message": "Después de cambiar la contraseña se reiniciará la sesión.",
    "Common_Popup_ChangePassword_Title": "Cambiar contraseña",
    "Common_PopupUrgent_Title": "Atender una urgéncia",
    "Common_Premium_Module": "Módulo PREMIUM",
    "Common_Previous": "Anterior",
    "Common_PrintExcel": "Imprimir en Excel",
    "Common_PrintPdf": "Imprimir en PDF",
    "Common_Profile": "Perfil",
    "Common_QR_Message": "Escanee el siguiente código QR con su aplicación móvil de verificación",
    "Common_QR_Popup_Title": "Verificación de identidad",
    "Common_RegisterCount": "Nº registros",
    "Common_Reload": "Mostrar",
    "Common_Report_Rendering": "Generando informe...",
    "Common_Required": "Obligatorio",
    "Common_Required_Title": "Revise los campos obligatorios",
    "Common_Responsible": "Responsable",
    "Common_Restore": "Restaurar",
    "Common_RightClickNotAllowed": "Botón derecho no permitido",
    "Common_Save": "Guardar",
    "Common_SaveAndContinue": "Guardar y continuar",
    "Common_Schedule": "Agenda",
    "Common_Search": "Buscar",
    "Common_Search_Filter": "Filtro de búsqueda",
    "Common_Searching": "Buscando...",
    "Common_Select": "Seleccionar",
    "Common_SelectAll_todos": "Seleccionar todos",
    "Common_Selected": "Seleccionado",
    "Common_SelectOne": "Seleccionar",
    "Common_Send": "Enviar",
    "Common_SessionTimeoutMessage": "Se ha superado el tiempo de inactividad",
    "Common_Settings": "Preferencias",
    "Common_ShowAll": "Ver todo",
    "Common_Status": "Estado",
    "Common_Success_Title": "Operación relizada con éxito",
    "Common_Target": "Objetivo",
    "Common_Task": "Tarea",
    "Common_Task_BtnNew": "Añadir tarea",
    "Common_Task_Title": "Tarea",
    "Common_Task_TitlePlural": "Tareas",
    "Common_ThisMonth": "Este mes",
    "Common_ThisWeek": "esta semana",
    "Common_TiemoutSessionTitle": "La sesión ha terminado",
    "Common_Time_Day": "día",
    "Common_Time_Month": "mes",
    "Common_Time_Week": "Semana",
    "Common_Time_Year": "año",
    "Common_TimeoutSessionMessage": "Se ha superado el tiempo permitido de inactividad",
    "Common_Title_Views": "Visualizaciones",
    "Common_Today": "Hoy",
    "Common_Total": "Total",
    "Common_Unactivated": "Desactivado",
    "Common_Undefined": "No definido",
    "Common_Unfollow": "Dejar de seguir",
    "Common_Unload": "Ocultar",
    "Common_Update": "Modificar",
    "Common_Upload_BtnOK": "Subir",
    "Common_Upload_BtnReSelect": "Seleccionar otro fichero",
    "Common_Upload_BtnSelect": "Seleccionar fichero",
    "Common_Upload_Label_CreatedOn": "Subido",
    "Common_Upload_Label_MIME": "Tipo",
    "Common_Upload_Label_NewName": "Nombre",
    "Common_Upload_Label_Size": "Tamaño",
    "Common_Upload_List_Header_Description": "Descripción",
    "Common_Upload_List_Header_Size": "Tamaño",
    "Common_Upload_List_Header_UploadedOn": "Fecha",
    "Common_Upload_NoSavedData": "Primero se deben guardar los datos",
    "Common_Upload_Popup_Title": "Subir fichero",
    "Common_Upload_Popup_Title_Prefix": "Subir fichero de",
    "Common_Upload_Popup_TitleAttach": "Adjuntar fichero",
    "Common_Upload_Success_Message": "Se ha guardado con el nombre",
    "Common_Upload_Success_Message2": "en el servidor.",
    "Common_Upload_Success_Title": "Fichero subido con éxito",
    "Common_Upload_Title_ActualFile": "Fichero actual",
    "Common_Upload_Title_NewFile": "Nuevo fichero",
    "Common_Upload_Tooltip_Delete": "Eliminar",
    "Common_Upload_Tooltip_Download": "Descargar",
    "Common_Upload_Tooltip_View": "Ver",
    "Common_Upload_UnknowType": "Tipo de fichero desconocido",
    "Common_User_Admin": "Administrador",
    "Common_User_Coporative": "Corporativo",
    "Common_User_Core": "Core",
    "Common_User_External": "Externo",
    "Common_User_Locked": "Bloqueado",
    "Common_User_Primary": "Primario",
    "Common_User_Technical": "Técnico",
    "Common_UserConversion_Popup_Title": "Crear usuario",
    "Common_UserConversionTable_Message": "Datos de conversión",
    "Common_UserPreferences": "Preferencias del usuario",
    "Common_UserProfile": "Perfil del usuario",
    "Common_View": "Ver",
    "Common_ViewAll": "Ver todo",
    "Common_ViewDetails": "Ver detalles",
    "Common_VoidData": "Sin datos",
    "Common_VoidSearchResult": "La búsqueda no ha encontrado datos",
    "Common_Warning": "Aviso",
    "Common_Warning_BrowserOld": "Se ha de actualizar el navegador",
    "Common_Warning_ImageRequired": "Se ha de seleccionar una imagen",
    "Common_Warning_ImageTooBig": "Imagen muy grande <br />Se ha de reducir el tamaño.",
    "Common_Warning_MimeType": "tipo de archivo no admitido",
    "Common_Warning_Undelete": "No se puede eliminar porque tiene registros asociados",
    "Common_Week": "Semana",
    "Common_WeekDay_Friday": "Viernes",
    "Common_WeekDay_Friday_Min": "vi",
    "Common_WeekDay_Friday_Short": "vi",
    "Common_WeekDay_Monday": "Lunes",
    "Common_WeekDay_Monday_Min": "lu",
    "Common_WeekDay_Monday_Short": "lu",
    "Common_WeekDay_Saturday": "Sábado",
    "Common_WeekDay_Saturday_Min": "sá",
    "Common_WeekDay_Saturday_Short": "sá",
    "Common_WeekDay_Sunday": "Domingo",
    "Common_WeekDay_Sunday_Min": "dm",
    "Common_WeekDay_Sunday_Short": "dm",
    "Common_WeekDay_Thursday": "Jueves",
    "Common_WeekDay_Thursday_Min": "ju",
    "Common_WeekDay_Thursday_Short": "ju",
    "Common_WeekDay_Tuesday": "Martes",
    "Common_WeekDay_Tuesday_Min": "ma",
    "Common_WeekDay_Tuesday_Short": "ma",
    "Common_WeekDay_Wednesday": "Miércoles",
    "Common_WeekDay_Wednesday_Min": "mi",
    "Common_WeekDay_Wednesday_Short": "mi",
    "Common_WeekDayName_Friday": "Viernes",
    "Common_WeekDayName_Monday": "Lunes",
    "Common_WeekDayName_Saturday": "Sábado",
    "Common_WeekDayName_Sunday": "Domingo",
    "Common_WeekDayName_Thursday": "Jueves",
    "Common_WeekDayName_Tuesday": "Martes",
    "Common_WeekDayName_Wednesday": "Miércoles",
    "Common_WeekDayShortName_Friday": "Viernes",
    "Common_WeekDayShortName_Monday": "lu",
    "Common_WeekDayShortName_Saturday": "sa",
    "Common_WeekDayShortName_Sunday": "dm",
    "Common_WeekDayShortName_Thursday": "ju",
    "Common_WeekDayShortName_Tuesday": "ma",
    "Common_WeekDayShortName_Wednesday": "mi",
    "Common_Welcome": "Hola",
    "Common_Welcome_Female": "Hola",
    "Common_Welcome_Male": "Hola",
    "Common_Working": "Acción en proceso",
    "Common_Year": "Año",
    "Common_Years": "Años",
    "Common_Yes": "Sí",
    "Core_AdminMode": "Admin",
    "Core_ApplicationUser_Btn_NewUser": "Añadir usuario",
    "Core_ApplicationUser_Btn_ResetPassword": "Reiniciar contraseña",
    "Core_ApplicationUser_Label_Admin": "Administrador",
    "Core_ApplicationUser_Label_BillingAccess": "Los usuarios del grupo tienen acceso a la contabilidad",
    "Core_ApplicationUser_Label_Core": "<strong><i>Core</i></strong>",
    "Core_ApplicationUser_Label_CreatedBy": "Creado por",
    "Core_ApplicationUser_Label_Email": "Email",
    "Core_ApplicationUser_Label_External": "Externo",
    "Core_ApplicationUser_Label_From": "Creación",
    "Core_ApplicationUser_Label_Last": "Último acceso",
    "Core_ApplicationUser_Label_Primary": "Primario",
    "Core_ApplicationUser_Label_RemindAlert": "Los usuarios del grupo pueden enviar un mensaje sobre una alerta",
    "Core_ApplicationUser_Label_Technical": "Técnico",
    "Core_ApplicationUser_MenuLabel": "Usuarios",
    "Core_ApplicationUser_Message_Admin": "Usuario con permisos de administración",
    "Core_ApplicationUser_Message_Core": "Usuario de OpenFramework, este usuario no se puede modificar ni eliminar.",
    "Core_ApplicationUser_Message_CoreGrants": "El usuario tiene acceso ilimitado a la aplicación y no es modificable.",
    "Core_ApplicationUser_Message_External": "Usuario externo a la empresa propietaria del framework",
    "Core_ApplicationUser_Message_GrantsByGroup": "Los permisos se otorgan a nivel de grupo.",
    "Core_ApplicationUser_Message_Primary": "Propietario de la instancia, es el usuario de contacto entre la empresa y OpenFramework",
    "Core_ApplicationUser_Message_Technical": "Usuario con capacidad de actuación técnica en la aplicación",
    "Core_ApplicationUser_NewUser": "<i>Nuevo usuario</i>",
    "Core_ApplicationUser_Profile_FirstName": "Nombre",
    "Core_ApplicationUser_Profile_LastName": "Apellido",
    "Core_ApplicationUser_Profile_LastName2": "Apellido 2",
    "Core_ApplicationUser_ScopeViewAll": "Sin restricciones",
    "Core_ApplicationUser_Tab_Activity": "Actividad",
    "Core_ApplicationUser_Tab_EffectiveGrants": "Permisos efectivos",
    "Core_ApplicationUser_Tab_Groups": "Pertenencia a grupos",
    "Core_ApplicationUser_Tab_Main": "Datos",
    "Core_ApplicationUser_Tab_Password": "Contraseña",
    "Core_ApplicationUser_Tab_SpecialGrants": "Permisos especiales",
    "Core_ApplicationUser_Title_Basic": "Datos del usuario",
    "Core_ApplicationUser_Title_GroupsAvailable": "Grupos disponibles",
    "Core_ApplicationUser_Title_GroupsSelected": "Seleccionados",
    "Core_ApplicationUser_Title_Membership": "Pertenencia a grupos",
    "Core_ApplicationUser_Title_ScopeView": "Ámbitos de acceso",
    "Core_ApplicationUser_Title_UserType": "Tipo de usuario",
    "Core_ApplicationUsers": "Usuarios de la aplicación",
    "Core_BackAccount_Label_PRE": "Fichero de descripción de la carga",
    "Core_BackUp_MenuLabel": "BackUp",
    "Core_BankAccount": "Cuenta bancaria",
    "Core_BankAccount_Btn_Add": "Aladir cuenta",
    "Core_BankAccount_ErrorMessage_BankNameRequired": "La entidad bancaria es obligatoria",
    "Core_BankAccount_ErrorMessage_IBANMalformed": "El código IBAN no tiene un formato correcto",
    "Core_BankAccount_ErrorMessage_IBANNotValid": "El código IBAN no es válido",
    "Core_BankAccount_ErrorMessage_IBANRequired": "El código IBAN es obligatorio",
    "Core_BankAccount_ErrorMessage_SWIFTRequired": "El código SWIFT es obligatorio",
    "Core_BankAccount_Header_Alias": "Alias",
    "Core_BankAccount_Header_BankName": "Entidad",
    "Core_BankAccount_Header_IBAN": "IBAN",
    "Core_BankAccount_Header_Main": "Principal",
    "Core_BankAccount_Header_Swift": "Swift",
    "Core_BankAccount_Label_Alias": "Alias",
    "Core_BankAccount_Label_BankName": "Entidd",
    "Core_BankAccount_Label_ContractId": "Id acreedor",
    "Core_BankAccount_Label_IBAN": "IBAN",
    "Core_BankAccount_Label_Main": "Cuenta principal",
    "Core_BankAccount_Label_PaymentType": "Tipo de cobro",
    "Core_BankAccount_Label_Swift": "SWIFT",
    "Core_BankAccount_List": "Listado de cuentas bancarias",
    "Core_BankAccount_Message_IsMain": "Esta cuenta es la principal",
    "Core_BankAccount_Title_Add": "Afegir cuenta bancaria",
    "Core_BankAccount_Title_Edit": "Editar cuenta bancaria",
    "Core_BankAccount_Title_Main": "Cuenta principal",
    "Core_BankAccount_Title_NoMain": "Cuenta no principal",
    "Core_BankAccounts": "Cuentas bancarias",
    "Core_Bill": "Factura",
    "Core_Billing": "Facturación",
    "Core_Billing_BtnNewInvoice": "Crear factura",
    "Core_Billing_Header_Amount": "Base",
    "Core_Billing_Header_BI": "Base&nbsp;I.",
    "Core_Billing_Header_Concept": "Concepto",
    "Core_Billing_Header_Discount": "Dto.",
    "Core_Billing_Header_IVA": "IVA",
    "Core_Billing_Header_PriceUnit": "Precio&nbsp;U.",
    "Core_Billing_Header_Quantity": "Cant.",
    "Core_Billing_Header_Total": "Total",
    "Core_Billing_List": "Listado",
    "Core_Billing_QuoteConceptLine": "Concepto",
    "Core_Billing_View": "Ver factura",
    "Core_BlockAction_Add": "Bloquear usuario",
    "Core_CalendarIcon_Title": "Calendario",
    "Core_ChangeUserMode": "Se actualizará la página con nueva configuración de usuario",
    "Core_ChangeUserModeTitle": "Cambio de modo de usuario",
    "Core_Company_CompanyAddress_ListHeader": "Direcciones",
    "Core_Company_ContactPerson_ListHeader": "Personas de contacto",
    "Core_Company_Header_Code": "Código",
    "Core_Company_Header_ContactMail": "Contacto",
    "Core_Company_Header_LOPD": "LOPD",
    "Core_Company_Header_Name": "Nombre",
    "Core_Company_Header_Status": "Estado",
    "Core_Company_Header_SubscriptionEnd": "Final",
    "Core_Company_Header_SubscriptionStart": "Inicio",
    "Core_Company_Profile": "Datos de empresa",
    "Core_CompanyAddress_Header_Billing": "Facturación",
    "Core_CompanyAddress_Header_Descripcion": "Dirección",
    "Core_CompanyAddress_Header_Main": "Principal",
    "Core_CompanyAddress_Title_Add": "Añadir dirección",
    "Core_CompanyAddress_Title_Billing": "Dirección de facturación",
    "Core_CompanyAddress_Title_Edit": "Editar dirección",
    "Core_CompanyAddress_Title_Main": "Dirección principal",
    "Core_CompanyAddress_Title_SetBilling": "Establecer como dirección de facturación",
    "Core_CompanyAddress_Title_SetMain": "Establecer como dirección principal",
    "Core_CompanyCustomConfig_MenuLabel": "Personalización",
    "Core_CompanyProfile_Label_Address": "Dirección",
    "Core_CompanyProfile_Label_CIF": "CIF",
    "Core_CompanyProfile_Label_Code": "Código",
    "Core_CompanyProfile_Label_Email": "Email",
    "Core_CompanyProfile_Label_Headquarters": "Razón social",
    "Core_CompanyProfile_Label_Name": "Nombre",
    "Core_CompanyProfile_Label_PostalCode": "Código postal",
    "Core_CompanyProfile_Label_Trademark": "Nombre comercial",
    "Core_CompanyProfile_Label_WayType": "Tipo de vía",
    "Core_CompanyProfile_Label_Web": "Web",
    "Core_CompanyProfile_MenuLabel": "Compañía",
    "Core_CompanyProfile_TabCompanyAddress": "Direcciones",
    "Core_CompanyProfile_TabContactPerson": "Persones de contacto",
    "Core_CompanyProfile_TabContract": "Contrato",
    "Core_CompanyProfile_TabCustomConfig": "Configuración personalizada",
    "Core_CompanyProfile_TabMain": "Datos principales",
    "Core_CompanyProfile_Title_Location": "Localización",
    "Core_CompanyProfile_Title_Risponsible": "Responsable centro",
    "Core_CompanyProgile_Title_BasicData": "Datos empresa",
    "Core_DataType_bool": "Sí/No",
    "Core_DataType_boolean": "Sí/No",
    "Core_DataType_datetime": "Fecha",
    "Core_DataType_decimal": "decimal",
    "Core_DataType_documentfile": "Documento",
    "Core_DataType_email": "Email",
    "Core_DataType_float": "Coma flotante",
    "Core_DataType_image": "Imagen",
    "Core_DataType_int": "Número entero",
    "Core_DataType_long": "Número largo",
    "Core_DataType_money": "Moneda",
    "Core_DataType_text": "Texto",
    "Core_DataType_textarea": "Texto largo",
    "Core_DataType_url": "Url",
    "Core_ImgUpload_BadFormatText": "Escoja una imagen en formato jpg|gif|png!",
    "Core_ImgUpload_BadFormatTitle": "El archivo no es una imagen.",
    "Core_ImgUpload_MaxSizeText": "Image size should not exceed 100Kb!",
    "Core_ImgUpload_MaxSizeTitle": "File too big!",
    "Core_Import_MenuLabel": "Importaciones",
    "Core_Instance_BasicData": "Configuración general",
    "Core_Instance_CommunicationsJSON": "Configuración JSON",
    "Core_Instance_ConfigurationJSON": "Fichero de configuración",
    "Core_Instance_CreateFile": "Generar fichero",
    "Core_Instance_Dictionary_Header_Key": "Clave",
    "Core_Instance_Dictionary_Label_Language": "Idioma",
    "Core_Instance_ExternalUsers": "Usuarios externos",
    "Core_Instance_FilesHeader_Dictionaries": "Diccionarios",
    "Core_Instance_FilesHeader_ScriptForm": "Script formulario",
    "Core_Instance_FilesHeader_ScriptList": "Script lista",
    "Core_Instance_Label_DefaultLanguage": "Idioma",
    "Core_Instance_Label_Description": "Descripción",
    "Core_Instance_Label_FAQs_Enabled": "Preguntas frecuentes habilitadas",
    "Core_Instance_Label_Identifier": "Identificador",
    "Core_Instance_Label_MultiCompany": "Multiempresa",
    "Core_Instance_Label_Name": "Nombre",
    "Core_Instance_Label_Timeout": "Timeout",
    "Core_Instance_Managment": "Gestión de instancia",
    "Core_Instance_Portal": "Portal",
    "Core_Instance_ScopeView": "Visualización por ámbitos activada",
    "Core_IPAccess_LabelCity": "Localidad",
    "Core_IPAccess_LabelCountry": "País",
    "Core_IPAccess_LabelIP": "IP de acceso",
    "Core_IPAccess_LabelISP": "ISP",
    "Core_IPAccess_LabelRegion": "Región",
    "Core_IPAccess_Message": "Si cree que debería tener acceso, póngase en contacto con",
    "Core_IPAccess_Title": "Acceso no permitido",
    "Core_Item_Feature_Hide": "Ocultable",
    "Core_Item_FieldsTab_Total": "Nº de campos",
    "Core_Item_FileNotExiste": "No existe el fichero",
    "Core_Item_FilesTab_Total": "Total ficheros",
    "Core_Item_FilesTab_TotalMessage": "Están creados <span id=\"\"totalFiles\"\">{0}</span> de {1} ficheros",
    "Core_Item_ListCompanyTableTab_Total": "Nº de compañías",
    "Core_Item_ScopeView": "Disponible para ámbito",
    "Core_Item_ScopeView_Tooltip": "Disponible para ámbitos",
    "Core_Item_ScopeView_Tooltip_Off": "No disponible para ámbitos",
    "Core_Item_Tab_Fields": "Campos",
    "Core_Item_Tab_ItemScript": "Script de ficha",
    "Core_Item_Tab_Json": "Defición del ítem",
    "Core_Item_Tab_ListScript": "Script de lista",
    "Core_Item_Tab_Main": "Datos básicos",
    "Core_MailBox_Btn_AddMailBox": "Añadir buzón",
    "Core_MailBoxes": "Buzones de correos",
    "Core_MailConfig_Header_Email": "Usuario",
    "Core_MailConfig_Header_Name": "Buzón",
    "Core_MailConfig_Header_Port": "Puerto",
    "Core_MailConfig_Header_Protocol": "Protocolo",
    "Core_Message_Alert": "Atención",
    "Core_Messaging_Add": "Añadir mensaje",
    "Core_Messaging_List": "Mensajes",
    "Core_Messaging_Title_MarkAsReaded": "Marcar como leído",
    "Core_Messaging_Title_ResponseToAuthor": "Responder el mensaje",
    "Core_MonthCalendar": "Agenda mensual",
    "Core_Profile_Label_AlternativeMail": "Email alternativo",
    "Core_Profile_Label_BirthDate": "F.nacimiento",
    "Core_Profile_Label_BitrhDate": "Fecha nacimiento",
    "Core_Profile_Label_Email": "Email",
    "Core_Profile_Label_EmergencyPhone": "Teléfono emergencia",
    "Core_Profile_Label_Fax": "Fax",
    "Core_Profile_Label_Gender": "Sexo",
    "Core_Profile_Label_IdentifyCard": "NIF/NIE/Pasaporte",
    "Core_Profile_Label_Mobile": "Móvil",
    "Core_Profile_Label_Nacionality": "Nacionalidad",
    "Core_Profile_Label_Phone": "Teléfono",
    "Core_Profile_NameFormat_Complete": "Nombre completo",
    "Core_Profile_NameFormat_FirstName2LastName": "Nombre y 2 apellidos",
    "Core_Profile_NameFormat_FirstNameLastName": "Nombre y 1er apellido",
    "Core_ScopeGroup_MenuLabel": "Grupos de ámbito",
    "Core_Security_CreateUser": "Crear usuario",
    "Core_SecurityGroup_Btn_AddSecurityGroup": "Añadir grupo",
    "Core_SecurityGroup_FieldLabel_Core": "Core",
    "Core_SecurityGroup_FieldLabel_Description": "Descripción",
    "Core_SecurityGroup_FieldLabel_Name": "Nombre",
    "Core_SecurityGroup_FieldLabel_Primary": "Principal",
    "Core_SecurityGroup_Header_Core": "Core",
    "Core_SecurityGroup_Header_Description": "Descripción",
    "Core_SecurityGroup_Header_Name": "Nombre",
    "Core_SecurityGroup_MenuLabel": "Grupos",
    "Core_SecurityGroup_Message_Core": "Grupo de <strong>OpenFramework</strong>, este grupo no se puede modificar ni eliminar.",
    "Core_SecurityGroup_Message_CoreGrants": "Este grupo forma parte del core de la aplicación, no se puede modificar",
    "Core_SecurityGroup_Message_SaveOk": "Grupo guardado con éxito",
    "Core_SecurityGroup_NewSecurityGroup": "Nuevo grupo",
    "Core_SecurityGroup_Tab_EffectiveGrants": "Permisos",
    "Core_SecurityGroup_Tab_Main": "Datos del grupo",
    "Core_SecurityGroup_Tab_Membership": "Miembros",
    "Core_SecurityGroup_Title_ApplicationUsersAvailable": "Disponibles",
    "Core_SecurityGroup_Title_ApplicationUsersSelected": "Pertenecientes",
    "Core_SecurityGroup_Title_Basic": "Datos",
    "Core_SecurityGroup_Title_Membership": "Miembros del grupo",
    "Core_SecurityGroup_Title_SpecialActions": "Acciones",
    "Core_SecurityGroup_Title_Type": "Tipo de grupo",
    "Core_SecurityGroups": "Grupos de seguridad",
    "Core_Sign_Message_CanceledByUser": "Firma cancelada por el usuario",
    "Core_Sign_Message_NoDevideDetected": "No se ha detectado el dispositivo para firmar",
    "Core_Suplantation_Button": "Suplantar usuario",
    "Core_Suplantation_Explanation": "Se actuará con los permisos y funcionalidades del usuario seleccionado.<br />Los datos se guardarán en nombre del usuario actual, no del suplantado.",
    "Core_SuplantationMode": "Suplente",
    "Core_Task_Button_AddNew": "Añadir tarea",
    "Core_TechincalMode": "Tech",
    "Core_Technical_Managment": "Gestión técnica",
    "Core_Traces_MenuLabel": "Trazabilidad",
    "Core_User_Btn_AddUser": "Añadir usuario",
    "Core_User_Header_Activity_Action": "Acción",
    "Core_User_Header_Activity_Date": "Fecha",
    "Core_User_Header_Activity_Item": "Ítem",
    "Core_User_Header_Grant_Delete": "Eliminación",
    "Core_User_Header_Grant_FAQs": "FAQs",
    "Core_User_Header_Grant_Hide": "Ocultar",
    "Core_User_Header_Grant_Import": "Importar",
    "Core_User_Header_Grant_Item": "Ítem",
    "Core_User_Header_Grant_News": "Noticias",
    "Core_User_Header_Grant_Read": "Lectura",
    "Core_User_Header_Grant_Write": "Modificación",
    "Core_User_ListHeader_Email": "Email",
    "Core_User_ListHeader_External": "Externo",
    "Core_User_ListHeader_FullName": "Nombre",
    "Core_UserMode": "Usuario sin privilegios",
    "Core_UserProfile_Btn_ChangePassword": "Cambiar contraseña",
    "Core_UserProfile_Btn_ChangeSignature": "Cambiar firma",
    "Core_UserProfile_Label_BirthDate": "F.nacimiento",
    "Core_UserProfile_Label_ChangeAvatar": "Cambiar avatar",
    "Core_UserProfile_Label_CreatedOn": "Creación",
    "Core_UserProfile_Label_EmailAlternative": "Email alternativo",
    "Core_UserProfile_Label_EmptyField": "vacío",
    "Core_UserProfile_Label_Facebook": "Facebook",
    "Core_UserProfile_Label_Fax": "Fax",
    "Core_UserProfile_Label_FullName": "Nombre",
    "Core_UserProfile_Label_Gender": "Sexo",
    "Core_UserProfile_Label_GenderFemale": "Mujer",
    "Core_UserProfile_Label_GenderGroup": "Grupo",
    "Core_UserProfile_Label_GenderMale": "Hombre",
    "Core_UserProfile_Label_History": "Historial",
    "Core_UserProfile_Label_IdentificationCard": "NIF/NIE/Pasaporte",
    "Core_UserProfile_Label_Instagram": "Instagram",
    "Core_UserProfile_Label_LastConnection": "Última conexión",
    "Core_UserProfile_Label_LinkedIn": "LinkedIn",
    "Core_UserProfile_Label_Location": "Localización",
    "Core_UserProfile_Label_Mobile": "Móvil",
    "Core_UserProfile_Label_ModifiedOn": "Última modificación",
    "Core_UserProfile_Label_Phone": "teléfono",
    "Core_UserProfile_Label_PhoneEmergency": "Teléfono emergencia",
    "Core_UserProfile_Label_Signature": "Firma",
    "Core_UserProfile_Label_Twiter": "Twiter",
    "Core_UserProfile_Label_UserName": "Usuario",
    "Core_UserProfile_Label_Web": "Sitio Web",
    "Core_UserProfile_Title_Activity": "Actividad reciente",
    "Core_UserProfile_Title_Contact": "Contacto",
    "Core_UserProfile_Title_ContactData": "Datos de contacto",
    "Core_UserProfile_Title_Favorites": "En seguimiento",
    "Core_UserProfile_Title_PersonalData": "Datos personales",
    "Core_UserProfile_Title_Preferences": "Preferencias",
    "Core_UserProfile_Title_Social": "Redes sociales",
    "Core_UserSuplantated": "A partir de ahora se actuará como el usuario",
    "Core_UserSuplantatedReturnedToMe": "A partir de ahora vuelves a ser tú mismo",
    "Core_UserSuplantatedReturnedToMeButton": "Volver a ser yo mismo",
    "Dictionary.Feature_Signature_Uploading": "Registrando firma...",
    "Dictionary_Manager": "Gestión de diccionarios",
    "Dictionary_ReloadDictionary": "Cargar diccionario",
    "Email": "Correo",
    "Feature_AdminRestriction": "Restringido a administradores",
    "Feature_AdminRestriction_Tooltip": "Solo administradores",
    "Feature_Alert_DataDescripcion": "Ítem implicado",
    "Feature_Alert_HeaderCategory": "Categoria",
    "Feature_Alert_LargeDescription": "Descripción",
    "Feature_Alert_Responsible": "Responsable",
    "Feature_Attachment_TabTitle": "Adjuntos",
    "Feature_Attachs": "Permet añadir adjuntos",
    "Feature_Attachs_Tooltip": "Admite adjuntos",
    "Feature_Attachs_Tooltip_Off": "Sin adjuntos",
    "Feature_BankAccount_BtnAdd": "Añadir cuenta bancaria",
    "Feature_BankAccount_HeaderAlias": "Alias",
    "Feature_BankAccount_HeaderEntidad": "Entidad",
    "Feature_BankAccount_HeaderIBAN": "IBAN",
    "Feature_BankAccount_HeaderPrincipal": "Principal",
    "Feature_BankAccount_HeaderSwift": "SWIFT",
    "Feature_BankAccount_MessageNoData": "No hay cuentas bancarias resgistradas",
    "Feature_BankAccount_TabTitle": "Cuentas bancarias",
    "Feature_BlockAction_IconTitle": "Bloquejar al professional fins que no resolgui l´alerta",
    "Feature_BlockAction_Label_SendTo": "Usuario a bloquear",
    "Feature_ContactPerson_BtnAdd": "Añadir contacto",
    "Feature_ContactPerson_Field_Email1": "Email 1",
    "Feature_ContactPerson_Field_Email2": "Email 2",
    "Feature_ContactPerson_Field_FirstName": "Nombre",
    "Feature_ContactPerson_Field_JobPosition": "Cargo",
    "Feature_ContactPerson_Field_LastName": "Apellido",
    "Feature_ContactPerson_Field_LastName2": "Apellido 2",
    "Feature_ContactPerson_Field_PhoneEmergency": "Tel.emergencia",
    "Feature_ContactPerson_Field_PhoneJob": "Tel.trabajo",
    "Feature_ContactPerson_Field_PhonePersonal": "Tel.personal",
    "Feature_ContactPerson_Field_Principal": "Principal",
    "Feature_ContactPerson_List_NoData": "No hay contactos",
    "Feature_ContactPerson_Popup_Title_Edit": "Modificar persona de contacto",
    "Feature_ContactPerson_Popup_Title_New": "Nueva persona de contacto",
    "Feature_ContactPerson_TabTitle": "Personas de contacto",
    "Feature_Document_AddWarning": "La creació d´un nou document substiruirà el vigent actual.<br />Vol continuar?",
    "Feature_DocumentSign_NoCreated": "Antes de firmar un documento se tiene que generar",
    "Feature_DocumentSign_NotSigned": "Falta firmar el documento",
    "Feature_DocumentSign_PageTitle": "Firma de documento",
    "Feature_DocumentSign_ReSign": "El documento ya está firmado. ¿Quiere volverlo a firmar?",
    "Feature_DocumentSign_SignatureMissing": "Pendiente de firmar",
    "Feature_FAQs": "FAQs activadas",
    "Feature_FAQs_BtnAdd": "Añadir pregunta",
    "Feature_FAQs_Header_Answer": "Respuesta",
    "Feature_FAQs_Header_ItemName": "Ítem",
    "Feature_FAQs_Header_Question": "Pregunta",
    "Feature_FAQs_Header_Status": "Estado",
    "Feature_FAQs_Label_Answer": "Respuesta",
    "Feature_FAQs_Label_Published": "Publicada en el portal",
    "Feature_FAQs_Label_Question": "Pregunta",
    "Feature_FAQs_Label_Target": "Objetivo",
    "Feature_FAQs_Label_Theme": "Tema",
    "Feature_FAQs_List_NoData": "No hay preguntas frecuentes",
    "Feature_FAQs_Status_Published": "Publicada",
    "Feature_FAQs_Status_Unpublished": "No publicada",
    "Feature_FAQs_TabTitle": "Preguntas frecuentes",
    "Feature_FAQs_Tooltip": "FAQs activadas",
    "Feature_FAQs_Tooltip_Off": "FAQs desctivadas",
    "Feature_Firmafy_TabTitle": "Firmafy",
    "Feature_Following": "Permite seguimiento",
    "Feature_Following_Tooltip": "Permite poner en seguimiento",
    "Feature_Following_Tooltip_Off": "No permite seguimiento",
    "Feature_Geolocation": "Permetre geolocalizacióm",
    "Feature_Geolocation_Tooltip": "Geolocalizable",
    "Feature_Geolocation_Tooltip_Off": "No geolocalizable",
    "Feature_Invoices_TabTitle": "Facturación",
    "Feature_Messagin_IconTitle": "Enviar missatge urgent al professional",
    "Feature_Messaging_Check_FromBoss": "Desde dirección",
    "Feature_Messaging_Check_SetAsImportant": "Marcar como importante",
    "Feature_Messaging_Label_Create": "Enviar mensaje",
    "Feature_Messaging_Label_Message": "Mensaje",
    "Feature_Messaging_Label_SendTo": "Enviar a",
    "Feature_Messaging_Label_Subject": "Asunto",
    "Feature_Messaging_List": "Mensajes recibidos",
    "Feature_Messaging_Message_MessageSent": "Se ha enviado el mensaje",
    "Feature_Messaging_Message_NoMessaged": "No hay mensajes",
    "Feature_Messaging_Message_RequiresResponse": "Este mensaje necesita una respuesta!",
    "Feature_Messaging_Message_Saved": "Mensaje enviado correctamente",
    "Feature_Messaging_Message_Saving": "Enviando mensaje",
    "Feature_Messaging_Title_FromBoss": "Mensaje enviado desde dirección, necesita respuesta",
    "Feature_News": "Noticies",
    "Feature_News_Add": "Añadir noticia",
    "Feature_News_Header_ItemName": "Tema",
    "Feature_News_Header_Publisher": "Autor",
    "Feature_News_Header_Status": "Estado",
    "Feature_News_Header_Title": "Título",
    "Feature_News_Status_Published": "Publicada",
    "Feature_Sign_Firmafy_Config": "Configuración Firmafy",
    "Feature_Sign_Firmafy_GetUserIdMessage": "Obteniendo usuario",
    "Feature_Sign_Firmafy_LoginMessage": "Accediendo a plataforma Firmafy",
    "Feature_Sign_Firmafy_SavingConfig": "Guardando configuración",
    "Feature_Sign_Firmafy_SendDocumentMessage": "Enviando solicitud de firma",
    "Feature_Sign_Popup_Title": "Firmar documento",
    "Feature_Sign_Wacom_NotAvailable": "Compruebe que el dispositivo está conectado al equipo. Y que en la pantalla aparece el dibujo de la imagen.",
    "Feature_Sign_Wacom_NotAvailable2": "Puede ver |aquí| el documento para descargar y firmar manualmente.",
    "Feature_Sticking_Add": "Añadir recordatorio",
    "Feature_Sticking_HeaderTitle": "Recordatorios",
    "Feature_Sticky": "Recordatorio",
    "Feature_Sticky_Label_Message": "Mensjae",
    "Feature_Sticky_Label_SendTo": "Visible por",
    "Feature_Tags": "Tags",
    "Feature_Tags_None": "No hay tags",
    "Feature_Tags_NoNumber": "No hay tags que empiecen per un número",
    "Feature_Tags_Void": "No hay tags que empiecen per",
    "Feature_WhatYouMissed": "Lo que te has perdido",
    "Feature_WhatYouMissed_Btn_SetViewd": "Marcar como vista",
    "Feature_WhatYouMissed_HeaderList_Affected": "ítem implicado",
    "Feature_WhatYouMissed_HeaderList_Category": "Categoria",
    "Feature_WhatYouMissed_HeaderList_Concept": "Concepto",
    "Feature_WhatYouMissed_HeaderList_Date": "Fecha",
    "Feature_WhatYouMissed_Message_NoData": "No hay nada pendiente de revisar",
    "Features_Alerts": "Alertas",
    "Features_FAQs": "Preguntas frecuentes (FAQs)",
    "Features_FAQs_BtnAdd": "Añadir FAQ",
    "Features_FAQs_Error_AnswerRequired": "Es necesario indicar la respuesta",
    "Features_FAQs_Error_QuestionRequired": "Es necesario indicar la pregunta",
    "Features_FAQs_Popup_Title_Edit": "Modificar FAQ",
    "Features_FAQs_Popup_Title_New": "Añadir FAQ",
    "Features_FAQs_PopupDelete_Title": "Eliminar FAQ",
    "Features_FAQs_Publish": "Publicar",
    "Features_FAQs_Unpublish": "Despublicar",
    "Features_Follow": "Permite seguimiento",
    "Features_Mail_Send": "Enviar per mail",
    "Features_MailLink": "Mails relacionados",
    "Features_Tags_Tooltip": "Tags activados",
    "Features_Tags_Tooltip_Off": "Tags desctivados",
    "Features_Title": "Funcionalides",
    "Features_Traces": "Acitvar trazas",
    "Features_Traces_Tooltip": "Trazas activadas",
    "Features_Traces_Tooltip_Off": "Trazas desctivadas",
    "Fin": "Fin",
    "Instance_Manager": "Gestión de instancia",
    "Instance_Manager_ReloadDefinitions": "Recargar definiciones",
    "Instance_Manager_ToggleCache_Disable": "Desactivar anti-caché",
    "Instance_Manager_ToggleCache_Enable": "Activar anti-caché",
    "Instance_Security_DeleteAction_Delete": "Borrar de la base de datos",
    "Instance_Security_DeleteAction_Inactivate": "Inactivar en la base de datos",
    "Instance_Security_DeleteAction_Title": "Eliminación de datos",
    "Instance_Security_GrantPerission_Title": "Otorgar pemisos",
    "Instance_Security_GrantPermissionBoth": "Se otorga a ambos niveles",
    "Instance_Security_GrantPermissionByGroup": "Se otorga nivel de grupo",
    "Instance_Security_GrantPermissionByUser": "Se otorga nivel de usuario",
    "Instance_Security_IPAccess": "IPAccess habilitado",
    "Instance_Security_MultimpleFactorAutentication": "Autentiación de múltiple factor",
    "Instance_Security_MultimpleFactorAutentication_APP": "Modo APP",
    "Instance_Security_MultimpleFactorAutentication_Email": "Modo eMail",
    "Instance_Security_MustResetPassword": "Cambiar contraseña tras primer inicio después de resetar",
    "Instance_Security_PasswordComplexity": "Complejidad",
    "Instance_Security_PasswordComplexity_None": "Ninguna",
    "Instance_Security_PasswordComplexity_NoneText": "Quilauier caracter",
    "Instance_Security_PasswordComplexity_Simple": "Simple",
    "Instance_Security_PasswordComplexity_SimpleText": "Al menos letras i números",
    "Instance_Security_PasswordComplexity_Strong": "Compleja",
    "Instance_Security_PasswordComplexity_StrongText": "Letras, números y caracteres especiales",
    "Instance_Security_PasswordComplexityResult_Good": "Débil",
    "Instance_Security_PasswordComplexityResult_Strong": "Robusta",
    "Instance_Security_PasswordComplexityResult_TooShort": "Muy corto",
    "Instance_Security_PasswordComplexityResult_Weak": "Muy débil",
    "Instance_Security_PasswordConfirmation": "No coincide",
    "Instance_Security_PasswordFailedAttemps": "Nº de intentos fallidos antes de bloquear acceso",
    "Instance_Security_PasswordMinimumLength": "Mínimo caracteres",
    "Instance_Security_PasswordPolicy": "Política de contraseñas",
    "Instance_Security_PinCode": "Pin Code",
    "Instance_Security_ScopeByGroup": "Según grupo de ámbito",
    "Instance_Security_ScopeByUser": "Según usuario",
    "Instance_Security_ScopeMode": "Modo de ámbito",
    "Instance_Security_Traceability_All": "De todo el sistema",
    "Instance_Security_Traceability_ByItem": "Por definición de ítem",
    "Instance_Security_Traceability_None": "Deshabilitada",
    "Instance_Security_Traceability_Title": "Trazabilidad",
    "Instance_Security_WriteAssumeDelete": "Permiso de escritura implica poder borrar",
    "Instance_Security_WriteAssumeDelete_Title": "Eliminación",
    "Instance_Security_WriteNotAssumeDelete": "Permiso de escritura y eliminación independientes",
    "Instance_Tab_Communications": "Comunicaciones",
    "Instance_Tab_Companies": "Compañías",
    "Instance_Tab_Contract": "Contrato",
    "Instance_Tab_Dictionary": "Diccionarios",
    "Instance_Tab_Files": "Ficheros",
    "Instance_Tab_FixedList": "Listas fijas",
    "Instance_Tab_IPAccess": "IPAccess",
    "Instance_Tab_Items": "Ítems",
    "Instance_Tab_Main": "Datos básicos",
    "Instance_Tab_Profile": "Perfil de usuario",
    "Instance_Tab_Security": "Seguridad",
    "Instance_UserProfile_NameFormat": "Formato",
    "Instance_UserProfile_UserName": "Nombre del usuario",
    "Item_Action_Popup_Details_Title": "Detalles de la acción",
    "Item_Alert_ListHeader_Description": "Descripción",
    "Item_Alert_ListHeader_Reason": "Motivo",
    "Item_Alerts": "Avisos",
    "Item_Almacen": "Centro",
    "Item_Almacen_Plural": "Centros",
    "Item_Alquiler": "Contrato",
    "Item_Alquiler_Plural": "Contratos",
    "Item_AlquilerSala": "Reserva",
    "Item_AlquilerSala_Plural": "Reservas",
    "Item_Attach_DiskFreeLabel1": "Disponible el",
    "Item_Attach_DiskFreeLabel2": "% de asignación de disco",
    "Item_Attach_DiskQuote": "Cuota de disco asignada:",
    "Item_Attach_FreeDisk": "Espacio disponible",
    "Item_Attach_Popup_Delete_Question": "¿Eliminar el adjunto?",
    "Item_Attach_Popup_Delete_Title": "Eliminar adjunto",
    "Item_Attachment_Btn_New": "Añadir documento",
    "Item_Attachment_CreateDate": "Subido el",
    "Item_Attachment_Description": "Descripción",
    "Item_Attachment_Header_CreateDate": "Subido el",
    "Item_Attachment_Header_Description": "Descripción",
    "Item_Attachment_Header_FileName": "Fichero",
    "Item_Attachment_Header_Size": "Tamaño",
    "Item_Attachment_Popup_Warning": "Esta acción no se puede deshacer",
    "Item_Attachment_SectionTitle": "Documentos adjuntos",
    "Item_Attachment_Size": "Tamaño",
    "Item_Backup": "Back-Up",
    "Item_Backup_Explain": "Explicar que es un backup para poder hacer una restauración o migrar datos a otra aplicación y tal...",
    "Item_Cliente": "Cliente",
    "Item_Cliente_Plural": "Clientes",
    "Item_Company_Button_CompanyAddressBAR": "Gestión de direcciones",
    "Item_Company_Help_Address": "Indicar la dirección, incluye el tipo de vía",
    "Item_Company_Help_BAR_Addresses": "Gestión de direcciones",
    "Item_Company_Help_City": "Indicar la población",
    "Item_Company_Help_Common_SelectAddress": "Seleccionar dirección",
    "Item_Company_Help_Email": "Indicar la dirección de correo electrónico",
    "Item_Company_Help_Fax": "Indicar el número de fax",
    "Item_Company_Help_Mobile": "Indicar el número de móvil",
    "Item_Company_Help_Name": "Nombre de la empresa",
    "Item_Company_Help_Nif": "Indicar el NIF",
    "Item_Company_Help_Pais": "Seleccionar el país",
    "Item_Company_Help_Phone": "Indicar el número de teléfono",
    "Item_Company_Help_Provincia": "Indicar la provincia",
    "Item_Company_Help_ZipCode": "Indicar el código postal",
    "Item_Company_Logo": "Logo",
    "Item_Company_Tab_Countries": "Países",
    "Item_Company_Tab_DiskQuote": "Uso de disco",
    "Item_Company_Tab_Principal": "Datos principales",
    "Item_Company_Tab_Traces": "Trazas",
    "Item_CompanyAddress_FieldLabel_Address": "Dirección",
    "Item_CompanyAddress_FieldLabel_Cellular": "Móvil",
    "Item_CompanyAddress_FieldLabel_City": "Población",
    "Item_CompanyAddress_FieldLabel_Country": "País",
    "Item_CompanyAddress_FieldLabel_PostalCode": "C.P.",
    "Item_CompanyAddress_FieldLabel_Province": "Provincia",
    "Item_CompanyAddress_FielLabel_Phone": "Teléfono",
    "Item_CompanyAddress_Header_Address": "Dirección",
    "Item_CompanyAddress_PopupDelete_Message": "¿Eliminar la dirección?",
    "Item_CompanyAddress_PopupTile_Add": "Añadir dirección",
    "Item_CompanyAddress_PopupTile_Edit": "Editar la dirección",
    "Item_CompanyAddress_PopupTitle": "Seleccionar una dirección principal",
    "Item_CompanyAddress_ToolTip_SetAsPrincipal": "Establecer como principal",
    "Item_CompanyCountries_Status_Availables": "Países disponibles",
    "Item_CompanyCountries_Status_Selected": "Países seleccionados",
    "Item_CompanyCountry_Button_Discard": "Descartar países",
    "Item_CompanyCountry_Button_Select": "Seleccionar países",
    "Item_CompanyCountry_FieldLabel_Name": "Nombre",
    "Item_CompanyData": "Datos Empresa",
    "Item_CompanyData_Button_ChangeLogo": "Cambiar el logo",
    "Item_CompanyData_Error_Message_PhoneOrCellular": "Indicar el teléfono fijo o el móvil",
    "Item_CompanyData_FieldLabel_Address": "Dirección",
    "Item_CompanyData_FieldLabel_Cellular": "Móvil",
    "Item_CompanyData_FieldLabel_City": "Localidad",
    "Item_CompanyData_FieldLabel_Country": "País",
    "Item_CompanyData_FieldLabel_Email": "Correo",
    "Item_CompanyData_FieldLabel_Fax": "Fax",
    "Item_CompanyData_FieldLabel_Phone": "Teléfono",
    "Item_CompanyData_FieldLabel_PostalAddress": "C.P.",
    "Item_CompanyData_FieldLabel_Province": "Provincia",
    "Item_CompanyData_Popup_ImageDelete_Title": "Eliminar la imagen",
    "Item_CompanyProfile_FieldLabel_Name": "Nombre",
    "Item_CompanyProfile_FieldLabel_Nif": "NIF",
    "Item_EstadoTrastero": "Estado de trastero",
    "Item_EstadoTrastero_Plural": "Estados de trastero",
    "Item_Facturador": "Facturador",
    "Item_Facturador_Plural": "Facturadores",
    "Item_Parking": "Parking",
    "Item_Parking_Plural": "Parking",
    "Item_Profile": "Perfil de usuario/a",
    "Item_Profile_FieldLabel_Address": "Dirección",
    "Item_Profile_FieldLabel_BirthDate": "F.nacimiento",
    "Item_Profile_FieldLabel_Email": "Correo",
    "Item_Profile_FieldLabel_Language": "Idioma",
    "Item_Profile_FieldLabel_Name": "Nombre",
    "Item_Profile_FieldLabel_Phone": "Teléfono",
    "Item_Profile_ShortCuts": "Botones de ayuda rápida",
    "Item_Profile_ShowHelp": "Ayuda en línea",
    "Item_Profile_Title_PersonalData": "Datos personales",
    "Item_Reports": "Informes",
    "Item_Review": "Revisión dirección",
    "Item_ScheduledTasks": "Tareas previstas",
    "Item_Tace_ListHeader_Date": "Fecha",
    "Item_Tace_ListHeader_Name": "Nombre",
    "Item_Tace_ListHeader_Reason": "Motivos",
    "Item_Tace_ListHeader_Trace": "Traza",
    "Item_Tace_ListHeader_User": "Usuario/a",
    "Item_Tarifa": "Tarifa",
    "Item_Tarifa_Plural": "Tarifas",
    "Item_TipoParking": "Tipo parking",
    "Item_TipoParking_Plural": "Tipos parking",
    "Item_TipoTrastero": "Tipo de trastero",
    "Item_TipoTrastero_Plural": "Tipos de trastero",
    "Item_Trace": "Traza",
    "Item_Trace_Active": "Activación",
    "Item_Trace_Created": "Creación",
    "Item_Trace_Delete": "Eliminación",
    "Item_Trace_LastActions": "Últimas acciones",
    "Item_Trace_Modify": "Modificación",
    "Item_Trace_Unactive": "Desactivación",
    "Item_Trace_Update": "Actualización",
    "Item_Trace_Updated": "Actualización",
    "Item_Traces": "Trazas",
    "Item_Trastero": "Trastero",
    "Item_Trastero_Plural": "Trasteros",
    "Item_User": "Usuario/a",
    "Item_User_ActualPassword": "Contraseña actual",
    "Item_User_Btn_ResetPassword": "Regenerar",
    "Item_User_Button_New": "Añadir",
    "Item_User_ChangePassword": "Cambiar la contraseña",
    "Item_User_ErrorMessage_PaswordsNoMatch": "Las contraseñas no coinciden",
    "Item_User_FieldLabel_PasswordConfirm": "Confirmar la contraseña",
    "Item_User_Help_PrimaryUser": "A este usuario no se le pueden modificar los permisos",
    "Item_User_Help_ResetPassword": "Se enviará la nueva contraseña al correo del usuario",
    "Item_User_List_Header_Email": "Correo",
    "Item_User_List_Header_EmployeeName": "Empleado/a",
    "Item_User_List_Header_Grant": "Permiso",
    "Item_User_List_Header_Read": "Lectura",
    "Item_User_List_Header_UserName": "Usuario/a",
    "Item_User_List_Header_Write": "Modificación",
    "Item_User_Message_AfterChangePassword": "Al cambiar la contraseña, se cerrará la sesión para reiniciar con la nueva contraseña",
    "Item_User_Message_GrantsAvaiable": "Se ha activado la pestaña de permisos. Por favor, activa los permisos necesarios para que el usuario pueda utilizar la aplicación.",
    "Item_User_Message_ResetPassword_Ok": "Contraseña regenerada correctamente. Se ha enviado un correo al usuario/a con las instrucciones de acceso a la aplicación.",
    "Item_User_Message_WelcommeMailSent": "Se ha enviado un correo al usuario/a con las instrucciones de acceso a la aplicación.",
    "Item_User_NewPassword": "Nueva contraseña",
    "Item_User_PopupDelete_Message": "¿Eliminar?",
    "Item_User_Profile_Title_Settings": "Configuración",
    "Item_User_Rol": "Rol",
    "Item_User_Suicide": "Un/a usuario/a no se puede eliminar a si mismo/a",
    "Item_User_Tab_Grants": "Permisos",
    "Item_User_Tab_Password": "Contraseña",
    "Item_User_Tab_Principal": "Datos básicos",
    "Item_User_Title_Account": "Gestión de la cuenta",
    "Item_User_Title_Add": "Ficha del/la Usuari/a",
    "Item_User_Title_ResetPassword": "Regenerar la contraseña",
    "Item_Users": "Usuarios/as",
    "MailTemplate_ResetPassword_DefaultBody": "Se ha reestablecido su contraseña en ISSUS.<br />Acceder a la siguiente url http://issus.scrambotika.com/ <br/> User:<b>{0}</b><br/>Password:<b>{1}</b>",
    "MailTemplate_ResetPassword_Error": "No se pudo reiniciar la contraseña",
    "MailTemplate_ResetPassword_Subject": "Reinicio de contraseña en ISSUS",
    "NumericDecimalSeparator": ",",
    "NumericMilesSeparator": ".",
    "Popup_ExportList_Btn_CSV": "CSV",
    "Popup_ExportList_Btn_Excel": "Excel",
    "Popup_ExportList_Btn_PDF": "PDF",
    "Popup_ExportList_Title": "Exportar listado",
    "Popup_FAQs_Label_Answer": "Respuesta",
    "Popup_FAQs_Label_Question": "Pregunta",
    "Popup_Image_Message": "La imagen se guardará sin necesidad de guardar el resto de datos del formulario.",
    "por": "por",
    "Principal": "Principal",
    "Resumen": "Resúmen",
    "semana": "semana",
    "Servicio": "Servicio",
    "Tipo": "Tipo",
    "User_Admin": "Administrador",
    "User_PrimaryUser": "Super Usuario/a",
    "-": "-"
};