// Autogenerated by OpenFramework Core, do not manually modify, under your resposability.
// Instance: NYRS - 10/10/2022 08:53:03
var ItemDefinitions = [
{
    "Id": 1,
    "ItemName": "Caso",
    "Layout": {
        "Icon": "fa fa-heartbeat",
        "Label": "Caso",
        "LabelPlural": "Casos",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Code" }
            ]
        },
        "EditionType": "inline"
    },
	"NeedFK": [],
	"ForeignValues": [],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Code", "Label": "Código", "Type": "text", "Length": 100 },
        { "Name": "EstudioStatus", "Label": "Código", "Type": "text", "Length": 5 },
        { "Name": "InvestigadorId", "Label": "Investigador", "Type": "text", "Length": 100 },
        { "Name": "UnidadId", "Label": "Unidad", "Type": "text", "Length": 100 },
        { "Name": "PacienteNombre", "Label": "Nombre", "Type": "text", "Length": 30 },
        { "Name": "PacienteApellidos", "Label": "Apellidos", "Type": "text", "Length": 50 },
        { "Name": "PacienteDNI", "Label": "DNI", "Type": "text", "Length": 15 },
        { "Name": "PacienteEdad", "Label": "Edad", "Type": "int" },
        { "Name": "PacienteTelefono", "Label": "Teléfono", "Type": "text", "Length": 15 },
        { "Name": "PacienteEmail", "Label": "Email", "Type": "email" },
		{ "Name": "PacienteSexo", "Label": "Sexo", "Type": "text", "Length": 1 },
		{ "Name": "PacienteNotificacion", "Label": "Notificación", "Type": "boolean" }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "PacienteSexo", "Label": "Tipo", "Width": 180, "Orderable":true, "Search": true, "Linkable": true, "RenderData": "CASO_Tipo" },
				{ "DataProperty": "Code","Width": 180, "Orderable":true, "Search": true,  },
				{ "DataProperty": "InvestigadorId", "Width":180, "Orderable":true, "Search": true },
				{ "DataProperty": "UnidadId", "Width":180, "Orderable":true, "Search": true },
				{ "DataProperty": "PacienteNombre", "Orderable":true, "Search": true, "RenderData": "CASO_PacienteNombreCompleto", },
				{ "DataProperty": "PacienteApellidos", "HiddenList": true },
				{ "DataProperty": "EstudioStatus", "HiddenList": true }
			]
        }
    ],
	"Forms": [  ]
}];