// Autogenerated by OpenFramework Core, do not manually modify, under your resposability.
// Instance: VIULLEURE - 22/03/2022 05:56:42
var ItemDefinitions = [
{
    "Id": 307,
    "ItemName": "Casal",
	"Features": {"Attachs": true, "Notes": true, "ScopeView": true, Sticky: true },
    "Layout": {
        "Icon": "fa fa-home-heart",
        "Label": "Activitat",
        "LabelPlural": "Activitats",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
	"NeedFK": [ "Monitor" ],
	"ForeignValues": [ {"ItemName": "TipoActividad"},{"ItemName": "CasalPeriodo"} ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripció", "Type": "textarea", "Length": 2000 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Online", "Label": "Online", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
        { "Name": "PhotoInscripcio", "Label": "Portada", "Type": "ImageFile" },
        { "Name": "LinkInscripcion", "Label": "Link inscripció", "Type": "DocumentFile" },
        { "Name": "LinkCovid", "Label": "Link responsabiltat", "Type": "DocumentFile" },
        { "Name": "MailInscripcion", "Label": "Adreça inscripció", "Type": "Email" },
        { "Name": "Fechas", "Label": "Dates", "Type": "text", "Required": true, "Length": 200 },
        { "Name": "Condiciones", "Label": "Condicions", "Type": "text", "Length": 500 },
        { "Name": "Promotor", "Label": "Promotor", "Type": "text", "Length": 500 },
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true },
        { "Name": "FechaLink", "Label": "Fecha inicio inscripcions", "Type": "datetime" },
        { "Name": "TipoActividadId", "Label": "Tipo", "Type": "long" },
        { "Name": "IBAN", "Label": "IBAN", "Type": "iban", "Length": 30 },
        { "Name": "Bizum", "Label": "Bizum", "Type": "text", "Length": 30 },
        { "Name": "Concepto", "Label": "Concepte", "Type": "text", "Length": 50 },
        { "Name": "BankName", "Label": "Entitat", "Type": "text", "Length": 50 },
		{ "Name": "Acollida1", "Label": "Acollida1", "Type": "money" },
		{ "Name": "Acollida2", "Label": "Acollida2", "Type": "money" },
		{ "Name": "Acollida3", "Label": "Acollida3", "Type": "money" },
		{ "Name": "Acollida4", "Label": "Acollida4", "Type": "money" },
		{ "Name": "Acollida5", "Label": "Acollida5", "Type": "money" },
		{ "Name": "Acollida6", "Label": "Acollida6", "Type": "money" },
		{ "Name": "Acollida7", "Label": "Acollida7", "Type": "money" },
		{ "Name": "Acollida8", "Label": "Acollida8", "Type": "money" },
		{ "Name": "Acollida9", "Label": "Acollida9", "Type": "money" },
		{ "Name": "DtoMunicipio", "Label": "Dt.Minucipi", "Type": "money" },
		{ "Name": "DtoHermanos", "Label": "Dt.Germans", "Type": "money" },
        { "Name": "QuorumMin", "Label": "Mínim", "Type": "int" },
        { "Name": "QuorumMax", "Label": "Màxim", "Type": "int" },
		{ "Name": "MetodoPago", "Label": "Pagament", "Type": "text", "Length": 10 },
		{ "Name": "DocRequerida", "Label": "DocumentacioRequerida", "Type": "text", "Length": 8 }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "TipoActividadId", "Orderable":true, "Width": 200 },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Online", "Orderable":true, "Width": 90 },
				{ "DataProperty": "FechaLink", "Orderable":true, "Width": 90, "Label": "Inici" }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
			"Actions": [
				{
					"Action": "INSCRIPCION_ListAcollida",
					"Icon": "fa fa-list",
					"Label": "Acollides",
					"Tab": "inscripcioneslist"
				},
				{
					"Action": "INSCRIPCION_FilterList",
					"Icon": "fa fa-list",
					"Label": "Llistats personalitzats",
					"Tab": "inscripcioneslist"
				},
				{
					"Action": "INSCRIPCION_GetMails",
					"Icon": "fa fa-envelope",
					"Label": "Mails dels tutors",
					"Tab": "inscripcioneslist"
				}
			],
            "Tabs": [
				{
					"Persistent": true,
					"Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" },
								{ "Name": "Online" }
							]
						}
					]
				},
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
                            "Fields": [
                                { "Name": "Descripcion", "ColSpan": 2 },
								{ "Name": "TipoActividadId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Fechas" },
                                { "Name": "QuorumMin" },
                                { "Name": "QuorumMax" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Promotor" },
                                { "Name": "Condiciones" , "ColSpan": 2 }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "DocRequerida", "Label": "Documentació" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "MetodoPago" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "DtoMunicipio" },
                                { "Name": "DtoHermanos"  },
								{ "Type": "Blank" }
                            ]
                        },
						{
							"Label": "Acollida",
							"Fields": [
								{ "Name": "Acollida", "Type": "Placeholder" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Acollida1", "Label": "Matinal / dia" },
                                { "Name": "Acollida2", "Label": "Matinal / set" },
                                { "Name": "Acollida3", "Label": "Matinal / casal " }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Acollida4", "Label": "Tarda / dia" },
                                { "Name": "Acollida5", "Label": "Tarda / set" },
                                { "Name": "Acollida6", "Label": "Tarda / casal" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Acollida7", "Label": "Matinal i tarda / dia" },
                                { "Name": "Acollida8", "Label": "Matinal i tarda / set" },
                                { "Name": "Acollida9", "Label": "Matinal i tarda / casal" }
                            ]
                        },
						{
							"Fields":[
								{"Name": "Notes", "Type": "Notes" }
							]
						}
					]
				},
				{
                    "Label": "Periodes",
                    "Id": "Periodes",
                    "Rows": [
						{
							"ItemList": "CasalPeriodo",
							"ListId": "ByCasal",
							"FilterFields": [ { "Field": "Actividad" } ]
						},
						{
							"ItemList": "CasalPeriodoPrecio",
							"ListId": "ByCasal",
							"FilterFields": [ { "Field": "Actividad" } ]
						}
					]
				},
				{
                    "Label": "Staff",
                    "Id": "staff",
                    "Rows": [
						{
							"ItemList": "CasalGrupo",
							"ListId": "ByCasal",
							"FilterFields": [ { "Field": "Actividad" } ]
						},
						{
							"ItemList": "CasalMonitorApoyo",
							"ListId": "ByCasal",
							"FilterFields": [ { "Field": "Actividad" } ]
						}
					]
				},
                {
                    "Label": "Web",
                    "Id": "Web",
                    "Rows": [
                        {
                            "Fields": [
								{ "Name": "Photo" },
								{ "Name": "Weight" }
                            ]
                        },
                        {
							"Label": "Inscripcio",
                            "Fields": [
								{ "Name": "PhotoInscripcio" },
								{ "Name": "LinkInscripcion" },
								{ "Name": "LinkCovid" }
                            ]
                        },
                        {
                            "Fields": [
								{ "Name": "MailInscripcion" },
								{ "Name": "FechaLink" }
                            ]
                        },
                        {	
							"Label": "Pagament",
                            "Fields": [
                                { "Name": "IBAN" },
                                { "Name": "BankName" }
                            ]
                        },
                        {	
                            "Fields": [
                                { "Name": "Bizum" },
                                { "Name": "Concepto" }
                            ]
                        }
					]
				},
                {
                    "Label": "Inscripciones",
                    "Id": "inscripcioneslist",
					"Rows": [
						{
							"ItemList": "Inscripcion",
							"ListId": "ByCasal",
							"FilterFields": [ { "Field": "Actividad" } ]
						}
                     ]
                },
                {
                    "Label": "Assignació de grups",
                    "Id": "AssignacioGrupos",
					"Rows": [
						{
							"Fields": [
								{ "Name": "Asignaciones", "Type": "Placeholder" }
							]
						}
                     ]
                }
			]
        }
	]
},
	{
    "Id": 102,
    "ItemName": "CasalGrupo",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-users",
        "Label": "Grup",
        "LabelPlural": "Grups",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"ForeignValues": [ {"ItemName": "Casal"} ,{"ItemName": "Monitor"} ,{"ItemName": "CasalPeriodo"}  ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "CasalId", "Label": "Actividad", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Length": 20, "Required": true },	
        { "Name": "MonitorId", "Label": "Monitor", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "CasalPeriodoId", "Label": "Periode", "Type": "long", "ColumnDataType": "Text", "FK": true },	
        { "Name": "Asistentes", "Label": "Assistents", "Type": "text", "Length": 200 }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 1,
            "Columns": [
                { "DataProperty": "CasalId", "Search": true, "Orderable": true, "Linkable": true, "Width": 250 },
                { "DataProperty": "Name", "Search": true },
                { "DataProperty": "MonitorId", "Search": true, "Width": 250 }
            ]
        },
        {
            "Id": "ByCasal",
            "FormId": "Custom",
			"Layout": 1,
			"Title": "Grups del casal",
			"EditAction": 2,
			"ForceHeight": 350,
			"NoDataMessage": "No hi ha grups a aquesta activitat",
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
            "Columns": [
                { "DataProperty": "Name", "Search": true },
                { "DataProperty": "CasalPeriodoId", "Search": true, "Width": 100 },
                { "DataProperty": "MonitorId", "Search": true, "Width": 250 },
                { "DataProperty": "Asistentes", "HiddenList": true }
            ],
			"Buttons": [
				{ "Name": "ViewProfile", "Label": "Veure dades", "Icon": "fal fa-user", "Function": "MONITOR_ViewProfileByGrupo"}
			]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
			"Explanation": "Els monitor en práctiques no es poden seleccionar",
            "Tabs": [
                {
                    "Id": "Data",
                    "Rows": [
                        {
							"Hidden": true,
                            "Fields": [
                                { "Name": "CasalId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Name" },
								{ "Name": "CasalPeriodoId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "MonitorId" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 110,
    "ItemName": "CasalGrupoAsignacion",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-users",
        "Label": "Grup",
        "LabelPlural": "Grups",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"ForeignValues": [ {"ItemName": "Casal"} ,{"ItemName": "Monitor"} ,{"ItemName": "CasalPeriodo"}  ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "CasalId", "Label": "Actividad", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Length": 20, "Required": true },	
        { "Name": "MonitorId", "Label": "Monitor", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "CasalPeriodoId", "Label": "Periode", "Type": "long", "ColumnDataType": "Text", "FK": true },	
        { "Name": "Asistentes", "Label": "Assistents", "Type": "text", "Length": 200 }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 1,
            "Columns": [
                { "DataProperty": "CasalId", "Search": true, "Orderable": true, "Linkable": true, "Width": 250 },
                { "DataProperty": "Name", "Search": true },
                { "DataProperty": "MonitorId", "Search": true, "Width": 250 }
            ]
        },
        {
            "Id": "ByCasal",
            "FormId": "Custom",
			"Layout": 1,
			"Title": "Grups del casal",
			"EditAction": 2,
			"ForceHeight": 350,
			"NoDataMessage": "No hi ha grups a aquesta activitat",
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
            "Columns": [
                { "DataProperty": "Name", "Search": true },
                { "DataProperty": "CasalPeriodoId", "Search": true, "Width": 100 },
                { "DataProperty": "MonitorId", "Search": true, "Width": 250 }
            ]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
			"Explanation": "Els monitor en práctiques no es poden seleccionar",
            "Tabs": [
                {
                    "Id": "Data",
                    "Rows": [
                        {
							"Hidden": true,
                            "Fields": [
                                { "Name": "CasalId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Name" },
								{ "Name": "CasalPeriodoId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "MonitorId" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 103,
    "ItemName": "CasalMonitorApoyo",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-users",
        "Label": "Monitor recolçament",
        "LabelPlural": "Monitors recolçament",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"ForeignValues": [ {"ItemName": "Casal"} ,{"ItemName": "Monitor"}  ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "CasalId", "Label": "Actividad", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "MonitorId", "Label": "Monitor", "Type": "long", "Required": true, "ColumnDataType": "text" }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 3,
            "Columns": [
                { "DataProperty": "CasalId", "Search": true, "Orderable": true, "Linkable": true, "Width": 250 },
                { "DataProperty": "MonitorId", "Search": true, "Width": 250 }
            ]
        },
        {
            "Id": "ByCasal",
            "FormId": "Custom",
			"Layout": 1,
			"EditAction": 2,
			"ForceHeight": 350,
			"Title": "Monitors de reforç",
			"NoDataMessage": "No hi ha grups a aquesta activitat",
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
            "Columns": [
                { "DataProperty": "MonitorId", "Search": true }
            ],
			"Buttons": [
				{ "Name": "ViewProfile", "Label": "Veure dades", "Icon": "fal fa-user", "Function": "MONITOR_ViewProfileByApoyo"}
			]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Id": "Data",
                    "Rows": [
                        {
							"Hidden": true,
                            "Fields": [
                                { "Name": "CasalId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "MonitorId" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 1307,
    "ItemName": "CasalPeriodo",
    "Layout": {
        "Icon": "fa fa-calendar",
        "Label": "Periode",
        "LabelPlural": "Periodes",
        "Description": {
            "Pattern": "{0} - {1}",
            "Fields": [
				{ "Name": "Code" },
				{ "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"ForeignValues": [ {"ItemName": "Casal"} ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Descripció", "Type": "textarea", "Length": 2000 },
        { "Name": "Code", "Label": "Codi", "Type": "text", "Length": 4, "FK": true },
        { "Name": "CasalId", "Label": "Casal", "Type": "long", "ColumnDataType": "Text", "FK": true },
        { "Name": "Disponible", "Label": "Disponible", "Type": "bool", "DataFormat": { "Name": "ToBooleanCheck" } }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "CasalId", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Name", "Width": 200 }
			]
        },
        {
			"Id": "ByCasal",
			"FormId": "Custom",
			"ForceHeight": 300,
			"Layout": 1,
			"EditAction": 2,
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "Code", "Width": 50 },
				{ "DataProperty": "Name" },
				{ "DataProperty": "Disponible", "Width": 100 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [				
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
							"Hidden": true,
                            "Fields": [
								{ "Name": "CasalId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Name" }
                            ]
                        },
                        {
                            "Fields": [
								{ "Name": "Code" },
								{ "Name": "Disponible" }
                            ]
                        }
					]
				
		}
	]
}]},
	{
    "Id": 1308,
    "ItemName": "CasalPeriodoPrecio",
    "Layout": {
        "Icon": "fa fa-euro",
        "Label": "Periode",
        "LabelPlural": "Periodes",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"ForeignValues": [ {"ItemName": "Casal"} ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Cantidad", "Label": "Quantitat", "Type": "int"},
        { "Name": "Precio", "Label": "Preu", "Type": "money"},
        { "Name": "CasalId", "Label": "Casal", "Type": "long", "ColumnDataType": "Text", "FK": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "CasalId", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Cantidad", "Orderable":true, "Width": 200 },
				{ "DataProperty": "Precio", "Orderable":true, "Width": 200 }
			]
        },
        {
			"Id": "ByCasal",
			"FormId": "Custom",
			"Layout": 1,
			"ForceHeight": 300,
			"EditAction": 2,
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "Cantidad", "Orderable":true, "Width": 200 },
				{ "DataProperty": "Precio", "Orderable":true }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [				
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
							"Hidden": true,
                            "Fields": [
								{ "Name": "CasalId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Cantidad" },
                                { "Name": "Precio" }
                            ]
                        }
					]
				
				}
			]
		}
	]
},
	{
    "Id": 5555,
  "ItemName": "Cliente",
  "Features": { "Attachs": true },
	"Description": "Clients",
    "Layout": {
        "Icon": "far fa-users",
        "Label": "Client",
        "LabelPlural": "Clients",
        "Description": {
            "Pattern": "{0}",
            "Fields": [ { "Name": "Nombre" } ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [ ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Nombre", "Label": "Nombre", "Type": "text", "Length": 150, "Required": true },
        { "Name": "CIF", "Label": "CIF", "Type": "text", "Length": 15 },
        { "Name": "Razon", "Label": "Razón social", "Type": "text", "Length": 150 },
		{ "Name": "EmailResponsable", "Label": "Email responsable", "Type": "email", "Length": 150, "Linkable": true },
		{ "Name": "EmailResponsable2", "Label": "Email responsable2", "Type": "email", "Length": 150, "Linkable": true },
		{ "Name": "NombreResponsable", "Label": "Nombre", "Type": "text", "Length": 150 },
		{ "Name": "NombreResponsable2", "Label": "Nombre", "Type": "text", "Length": 150 },
		{ "Name": "TelefonoResponsable", "Label": "Telefono", "Type": "text", "Length": 15 },
		{ "Name": "TelefonoResponsable2", "Label": "Telefono", "Type": "text", "Length": 15 },
		{ "Name": "CargoResponsable", "Label": "Cargo", "Type": "text", "Length": 50 },
		{ "Name": "CargoResponsable2", "Label": "Cargo", "Type": "text", "Length": 50}
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
			"Importable": true,
            "EditAction": 3,
            "Columns": [
                { "DataProperty": "Nombre", "Search": true, "Orderable": true, "Linkable": true },
                { "DataProperty": "CIF", "Search": true, "Orderable": true, "Linkable": true, "Width": 120 },
                { "DataProperty": "EmailResponsable", "Width": 200 }
            ]
        }
    ],
    "Forms": [
        {
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
					"Rows": [
						{
							"Fields": [
								{ "Name": "Nombre", "ColSpan": 2 },
								{ "Name": "CIF" }
							]
						},
						{
							"Fields": [
								{ "Name": "Razon" },
							]
						},
						{
							"Label": "Responsable 1",
							"Fields": [
								{ "Name": "NombreResponsable", "ColSpan": 2 },
								{ "Name": "CargoResponsable" }
							]
						},
						{
							"Fields": [
								{ "Name": "EmailResponsable", "ColSpan": 2 },
								{ "Name": "TelefonoResponsable" }
							]
						},
						{
							"Label": "Responsable 2",
							"Fields": [
								{ "Name": "NombreResponsable2", "ColSpan": 2},
								{ "Name": "CargoResponsable2" }
							]
						},
						{
							"Fields": [
								{ "Name": "EmailResponsable2", "ColSpan": 2 },
								{ "Name": "TelefonoResponsable2" }
							]
						}
					]
                },
                {
                    "Label": "Licitaciones",
                    "Id": "Licitaciones",
					"MustExists": true,
					"Rows": [
						{
							"ItemList": "Licitacion",
							"ListId": "ByCliente",
							"ForceHeight": 600,
							"FilterFields": [ { "Field": "Cliente" } ]
						}
					]
				}
            ]
        }
    ]
},
	{
    "Id": 303,
    "ItemName": "Colaboracion",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Colaboració",
        "LabelPlural": "Colaboracions",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
        { "Name": "Web", "Label": "Web", "Type": "Url" },
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Dades",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" }
							]
						},
                        {
                            "Fields": [
								{ "Name": "Web" }
                            ]
                        },
                        {
                            "Fields": [
								{ "Name": "Photo" },
								{ "Name": "Weight" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 306,
    "ItemName": "Destacado",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Destacat",
        "LabelPlural": "Destacats",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripción", "Type": "text", "Length": 200 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Descripcion", "Orderable":true, "Width": 400 },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Descripcion" }
                            ]
                        },
                        {
                            "Fields": [
								{ "Name": "Photo" },
								{ "Name": "Weight" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 54354,
    "ItemName": "EstadoLicitacion",
    "Layout": {
        "Icon": "fa fa-gear",
        "Label": "Estado de las licitaciones",
        "LabelPlural": "Estados de las licitaciones",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nombre", "Type": "text", "Length": 50, "Required": true }
    ]
},
	{
    "Id": 300,
    "ItemName": "Evento",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Event",
        "LabelPlural": "Events",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripción", "Type": "text", "Length": 100 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Descripcion", "Orderable":true, "Width": 400 },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Descripcion" }
                            ]
                        },
                        {
                            "Fields": [
								{ "Name": "Photo" },
								{ "Name": "Weight" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 308,
    "ItemName": "Inscripcion",
	"Features": { Sticky: true },
    "Description": "Inscripción a un casal",
    "Layout": {
        "Icon": "fa fa-list",
        "Label": "Inscripción",
        "LabelPlural": "Inscripciones",
        "Description": {
            "Pattern": "{0} {1}",
            "Fields": [
                { "Name": "AsistenteNombre" },
				{ "Name": "AsistenteApellidos" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [
        { "ItemName": "Casal" }
    ],
	"NeedFK": [ "CasalPeriodo" ],
    "PrimaryKeys": [ ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Code", "Label": "Codi", "Type": "text", "Length": 20, "Required": true },
        { "Name": "CasalId", "Label": "Actividad", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "FechaSolicitud", "Label": "Preinscripción", "Type": "datetime", "Required": true },
        { "Name": "FechaConfirmacion", "Label": "Confirmación", "Type": "datetime" },
        { "Name": "Status", "Label": "Estat", "Type": "int" },
        { "Name": "PaymentStatus", "Label": "Estat pagament", "Type": "int" },
        { "Name": "StatusText", "Label": "Text per al inscrit", "Type": "textarea", "Length": 1000 },
		
        { "Name": "DocSolicitut", "Label": "Sol·licitut", "Type": "DocumentFile" },
        { "Name": "DocSolicitutFilled", "Label": "Sol·licitut", "Type": "DocumentFile" },
        { "Name": "DocDNITutor", "Label": "DNI tutor", "Type": "DocumentFile" },
        { "Name": "DocLibroFamilia", "Label": "Llibre familia", "Type": "DocumentFile" },
        { "Name": "DocTarjetaSanitaria", "Label": "Tarjeta sanitaria", "Type": "DocumentFile" },
        { "Name": "DocVacunas", "Label": "Vacunes", "Type": "DocumentFile" },
        { "Name": "DocDGJ", "Label": "DGJ", "Type": "DocumentFile" },
        { "Name": "DocInformeMedico", "Label": "Informe mèdic", "Type": "DocumentFile" },
        { "Name": "DocPagament", "Label": "Pagament", "Type": "DocumentFile" },
		
        { "Name": "AsistenteNombre", "Label": "Nombre", "Type": "text", "Length": 20 },
        { "Name": "AsistenteApellidos", "Label": "Apellidos", "Type": "text", "Length": 50 },
        { "Name": "FNac", "Label": "D.Naixement", "Type": "datetime" },
        { "Name": "Curso", "Label": "Curs", "Type": "text", "Length": 1000 },
		
        { "Name": "TutorNombre", "Label": "Nombre", "Type": "text", "Length": 20 },
        { "Name": "TutorApellidos", "Label": "Apellidos", "Type": "text", "Length": 50 },
        { "Name": "TutorNIF", "Label": "NIF", "Type": "text", "Length": 15 },
        { "Name": "TurorEmail", "Label": "Email", "Type": "text", "Length": 150 },
        { "Name": "TutorTelefono", "Label": "Telèfon", "Type": "text", "Length": 15 },
        { "Name": "TutorDireccion", "Label": "Adreça", "Type": "text", "Length": 150 },
        { "Name": "TutorPoblacion", "Label": "Població", "Type": "text", "Length": 50 },
		
        { "Name": "SaludEnfermedades", "Label": "Malalties", "Type": "text", "Length": 50 },
        { "Name": "SaludMedicamentos", "Label": "Medicació", "Type": "text", "Length": 50 },
        { "Name": "SaludAlergia", "Label": "Al·lèrgies", "Type": "text", "Length": 50 },
        { "Name": "SaludDieta", "Label": "Dieta", "Type": "text", "Length": 50 },
        { "Name": "NecesidadesEspeciales", "Label": "Necessitats especials", "Type": "textarea", "Length": 2000 },
        { "Name": "Observaciones", "Label": "Observacions", "Type": "textarea", "Length": 2000 },
        { "Name": "Vista", "Label": "Vista/oïda", "Type": "text", "Length": 50 },
        { "Name": "Insomnio", "Label": "Insomni", "Type": "text", "Length": 50 },
        { "Name": "Enuresi", "Label": "Enuresi", "Type": "text", "Length": 50 },
        { "Name": "Ortopedia", "Label": "Ortopedia", "Type": "text", "Length": 50 },
        { "Name": "Psico", "Label": "Dificultat", "Type": "text", "Length": 50 },
        { "Name": "Cansancio", "Label": "Cansancio", "Type": "text", "Length": 50 },
        { "Name": "Periodos", "Label": "Periodes", "Type": "text", "Length": 50 },
        { "Name": "Acollida", "Label": "Acollida", "Type": "long" },
		
        { "Name": "AutorizacionActividades", "Label": "Autorització activitats", "Type": "bool" },
        { "Name": "AutorizacionImagen", "Label": "Autorització imatge", "Type": "bool" },
        { "Name": "AutorizacionTraslado", "Label": "Autorització trasllat centre mèdic", "Type": "bool" },
        { "Name": "DtoMunicipio", "Label": "Dt.Municipi", "Type": "bool" },
        { "Name": "DtoHermanos", "Label": "Dt.Germans", "Type": "bool" },
        { "Name": "PrecioCuota", "Label": "Preu", "Type": "money" },
        { "Name": "PrecioAcollida", "Label": "Acollida", "Type": "money" },
        { "Name": "DocSolicitutSignada", "Label": "Sol.licitut signada", "Type": "bool" },
        { "Name": "Signatura", "Label": "Signatura", "Type": "imagefile" },
        { "Name": "MetodoPago", "Label": "MPago", "Type": "text", "Length": 1 }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "CasalId", "Width": 200, "Orderable": true },
				{ "DataProperty": "AsistenteNombre", "Search": true, "RenderData": "ASISTENTE_NombreCompleto", "Linkable": true },
				{ "DataProperty": "Curso", "Width": 90, "Search": true  },
				{ "DataProperty": "Status", "Width": 120, "RenderData": "INSCRIPCION_Status", "Align": "Left", "Search": true },
				{ "DataProperty": "Code", "Width": 150 , "Search": true, "Linkable": true },
				{ "DataProperty": "AsistenteApellidos", "Search": true, "HiddenList": true }
          ]
        },
        {
			"Id": "ByCasal",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"NoDataMessage": "No hi ha inscripcions a aquesta activitat",
			"Parameters": [ {"Name": "CasalId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "AsistenteNombre", "Search": true, "RenderData": "ASISTENTE_NombreCompleto", "Orderable": true, "Linkable": true },
				{ "DataProperty": "Periodos", "Width": 180, "RenderData": "INSCRIPCION_Periodos", "Align": "Left", "Search": true },
				{ "DataProperty": "Curso", "Width": 90, "Search": true  },
				{ "DataProperty": "Status", "Width": 120, "RenderData": "INSCRIPCION_Status", "Align": "Left", "Search": true },
				{ "DataProperty": "Code", "Width": 150 , "Search": true },
				{ "DataProperty": "Signatura", "Width": 150 , "Search": true, "Linkable": true },
				{ "DataProperty": "AsistenteApellidos", "Search": true, "HiddenList": true },
				{ "DataProperty": "TurorEmail", "Search": true, "HiddenList": true }
			]
        }
    ],
	"Forms":
	[
		{
			"Id": "Custom",
			"FormType": "Custom",
			"Tabs": 
			[
				{
					"Label": "Datos",
					"Rows": [
						{
							"Fields": [
								{ "Name": "CasalId", "ColSpan": 2 },
								{ "Name": "DocSolicitutSignada" }
							]
						},
						{
							"Fields": [
								{ "Name": "Code" },
								{ "Name": "FechaSolicitud" },
								{ "Name": "Signatura" }
							]
						},
						{
							"Fields": [
								{ "Name": "Periodos" }
							]
						},
						{
							"Fields": [
								{ "Name": "Status" }
							]
						},
						{
							"Fields": [
								{ "Name": "StatusText" }
							]
						},
						{
							"Fields": [
								{ "Name": "PrecioCuota" },
								{ "Name": "DtoMunicipio" },
								{ "Name": "DtoHermanos" }
							]
						},
						{
							"Fields": [
								{ "Name": "PrecioAcollida" },
								{ "Name": "Acollida", "ColSpan": 2 }
							]
						},
						{
							"Label": "Autorització",
							"Fields": [
								{ "Name": "AutorizacionActividades" },
								{ "Name": "AutorizacionImagen" },
								{ "Name": "AutorizacionTraslado" }
							]
						},
						{
							"Label": "Assistent",
							"Fields": [
								{ "Name": "AsistenteNombre" },
								{ "Name": "AsistenteApellidos", "ColSpan": 2 }
							]
						},
						{
							"Fields": [
								{ "Name": "FNac" },
								{ "Name": "Curso" },
								{ "Type": "Blank" }
							]
						},
						{
							"Fields": [
								{ "Name": "NecesidadesEspeciales" }
							]
						},
						{
							"Fields": [
								{ "Name": "Observaciones" }
							]
						},
						{
							"Label": "Tutor",
							"Fields": [
								{ "Name": "TutorNombre" },
								{ "Name": "TutorApellidos" },
								{ "Name": "TutorNIF" }
							]
						},
						{
							"Fields": [
								{ "Name": "TutorDireccion", "ColSpan": 2 },
								{ "Name": "TutorPoblacion" }
							]
						},
						{
							"Fields": [
								{ "Name": "TurorEmail", "ColSpan": 2 },
								{ "Name": "TutorTelefono" }
							]
						}
					]
				},
				{
					"Label": "Documentació",
					"Rows": [
						{
							"Fields": [
								{ "Name": "DocSolicitut","Config": "LVUS" },
								{ "Name": "DocPagament", "Config": "LVU" }
							]
						},
						{
							"Fields": [
								{ "Name": "DocDNITutor","Config": "LVU" },
								{ "Name": "DocLibroFamilia", "Config": "LVU"}
							]
						},
						{
							"Fields": [
								{ "Name": "DocTarjetaSanitaria", "Config": "LVU" },
								{ "Name": "DocVacunas", "Config": "LVU" }
							]
						},
						{
							"Fields": [
								{ "Name": "DocDGJ", "Config": "LVU" },
								{ "Name": "DocInformeMedico", "Config": "LVU"}
							]
						}
					]
				},
				{
					"Label": "Fitxa salut",
					"Rows": [
						{
							"Fields": [
								{ "Name": "SaludEnfermedades" },
								{ "Name": "SaludMedicamentos" }
							]
						},
						{
							"Fields": [
								{ "Name": "SaludAlergia" },
								{ "Name": "SaludDieta" }
							]
						},
						{
							"Fields": [
								{ "Name": "Vista" },
								{ "Name": "Insomnio" }
							]
						},
						{
							"Fields": [
								{ "Name": "Enuresi" },
								{ "Type": "Blank" }
							]
						},
						{
							"Fields": [
								{ "Name": "Psico" },
								{ "Name": "Cansancio" }
							]
						}
					]
				}
			]
		}
	]
},
	{
    "Id": 200,
    "ItemName": "Learning",
	"Features": { "Attachs": true },
    "Layout": {
        "Icon": "fa fa-chalkboard-teacher",
        "Label": "Curs",
        "LabelPlural": "Cursos",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"NeedFK": [ "Core_User", "LearningTeacher" ],
    "ForeignValues": [ { "ItemName":"LearningStatus" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripción", "Type": "textarea", "Length": 2000 },
        { "Name": "Target", "Label": "Dirigit a", "Type": "textarea", "Length": 2000 },
        { "Name": "Objective", "Label": "Objectiu", "Type": "textarea", "Length": 2000 },
        { "Name": "Contents", "Label": "Contingut", "Type": "textarea", "Length": 2000 },
        { "Name": "Methodogy", "Label": "Metodologia", "Type": "textarea", "Length": 2000 },
        { "Name": "Notes", "Label": "Notas", "Type": "textarea", "Length": 2000 },
        { "Name": "IBAN", "Label": "IBAN", "Type": "IBAN" },
        { "Name": "Amount", "Label": "Cost", "Type": "money" },
        { "Name": "Evaluable", "Label": "Evaluable", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Presencial", "Label": "Presencial", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Online", "Label": "OnLine", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "InscriptionStart", "Label": "Inici inscripcions", "Type": "datetime" },
		{ "Name": "InscriptionEnd", "Label": "Fi d'inscripcions", "Type": "datetime" },
		{ "Name": "LearningStatusId", "Label": "Status", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
		{ "Name": "MetodoPago", "Label": "Pagament", "Type": "text", "Length": 10 }
    ],
    "Lists": [
        {
          "Id": "Custom",
          "FormId": "Custom",
          "Layout": 1,
          "Exportable": false,
          "EditAction": 3,
          "Columns": [
            { "DataProperty": "Name", "Orderable":true, "Search": true, "Linkable": true },
            { "DataProperty": "InscriptionStart", "Orderable":true, "Width": 120 },
            { "DataProperty": "InscriptionEnd", "Orderable":true, "Width": 120 },
            { "DataProperty": "LearningStatusId", "Orderable":true, "Width": 150 }
          ]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Name", "ColSpan": 3 },
								{ "Name": "LearningStatusId" }
							]
						},
						{
							"Fields": [
								{ "Name": "Presencial" },
								{ "Name": "Online" },
								{ "Name": "Evaluable" },
								{ "Type": "Blank" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Descripcion" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "InscriptionStart" },
								{ "Name": "InscriptionEnd" },
								{ "Name": "Photo", "ColSpan": 2 }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "IBAN", "ColSpan": 2 },
								{ "Type": "Blank" }
							]
                        },
                        {
                            "Fields": [
								{ "Name": "Amount" },
								{ "Name": "MetodoPago", "ColSpan": 2 }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Notes" }
                            ]
                        },
						{
							"ItemList": "LearningTeacherAssignation",
							"ListId": "ByLearning",
							"FilterFields": [ { "Field": "Learning" } ]
						}
					]
				},
                {
                    "Label": "Inscripcions",
                    "Id": "inscripcioneslist",
					"Rows": [
						{
							"ItemList": "LearningAssistant",
							"ListId": "ByLearning",
							"FilterFields": [ { "Field": "Learning" } ]
						}
                     ]
                },
				{
					"Label": "Acció formativa",
					"Id": "LearningDefinition",
					"Rows": [
                        {
                            "Fields": [
                                { "Name": "Target" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Contents", "Wysiwyg": true }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Objective" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Methodogy" }
                            ]
                        }
                    ]
				},
				{
					"Label": "Calendari",
					"Id": "Calendari",
					"Rows": [
						{
							"ItemList": "LearningSeasson",
							"ListId": "ByLearning",
							"FilterFields": [ { "Field": "Learning" } ]
						}
                    ]
				},
				{
					"Label": "Participants",
					"Id": "Participants",
					"Rows": [
						{
							"ItemList": "LearningAssistant",
							"ListId": "ByLearning",
							"FilterFields": [ { "Field": "Learning" } ]
						}
                    ]
				}
            ]
        }
	]
},
	{
    "Id": 205,
    "ItemName": "LearningAssistant",
    "Layout": {
        "Icon": "fa fa-user-graduate",
        "Label": "Asistent",
        "LabelPlural": "Asistents",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [ { "ItemName":"Learning" }, { "ItemName": "Core_User" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "LearningId", "Label": "Curs", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Length": 50, "Required": true },
        { "Name": "FirstName", "Label": "Cognoms", "Type": "text", "Length": 50, "Required": true },
        { "Name": "NIF", "Label": "NIF", "Type": "text", "Length": 15, "Required": true },
        { "Name": "Gender", "Label": "Gènere", "Type": "text", "Length": 15, "Required": true },
        { "Name": "TutorName", "Label": "Nom tutor", "Type": "text", "Length": 50 },
        { "Name": "TutorFirstName", "Label": "Cognoms tutor", "Type": "text", "Length": 50 },
        { "Name": "TutorNIF", "Label": "TutorNIF", "Type": "text", "Length": 15 },
        { "Name": "Phone", "Label": "Telèfon", "Type": "text", "Length": 15, "Required": true },
        { "Name": "TutorPhone", "Label": "Telèfon tutor", "Type": "text", "Length": 15 },
        { "Name": "Birthday", "Label": "Naixement", "Type": "datetime", "Required": true },
        { "Name": "Email", "Label": "Email", "Type": "email" },
		{ "Name": "Address", "Label": "Adreça", "Type": "text", "Length": 100, "Required": true },
		{ "Name": "LocationPostalCodeId", "Label": "C.P. Localitat", "Type": "Long", "Required": true },
		{ "Name": "Special", "Label": "TracteEspecial", "Type": "text", "Length": 100 },
		{ "Name": "Conocio", "Label": "Com es va conèixer", "Type": "text", "Length": 100 },
		{ "Name": "LOPD", "Label": "LOPD", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "RRSS", "Label": "RRSS", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "InscriptionDate", "Label": "Sol·licitut", "Type": "datetime" },
		{ "Name": "AccessDate", "Label": "Inscripció", "Type": "datetime" },
		{ "Name": "Finished", "Label": "Finalitzat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "Evaluated", "Label": "Evalutat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "BoolEvaluation", "Label": "Evaluació", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "NumericEvaluation", "Label": "Evaluació", "Type": "int" },
		{ "Name": "TextEvaluation", "Label": "Evaluació", "Type": "text", "Length": 100 },
		{ "Name": "Signature", "Label": "Signatura", "Type": "imagefile", "Length": 100 },
		{ "Name": "DNI1", "Label": "DNI anvers", "Type": "DocumentFile", "Length": 100 },
		{ "Name": "DNI2", "Label": "DNI revers", "Type": "DocumentFile", "Length": 100 },
		{ "Name": "TS", "Label": "Tarjeta sanitària", "Type": "DocumentFile", "Length": 100 },
		{ "Name": "Core_UserId", "Label": "Usuari", "Type": "applicationUser" }
		
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 2,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true }
            ]
        },
        {
			"Id": "ByLearning",
			"FormId": "Custom",
			"Layout": 1,
            "EditAction": 3,
			"Title": "Asistents",
			"Parameters": [ {"Name": "LearningId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "Name", "Width": 100, "Orderable":true },
				{ "DataProperty": "FirstName", "Orderable":true },
				{ "DataProperty": "Phone", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Email", "Orderable":true, "Width": 200 },
				{ "DataProperty": "Finished", "Orderable":true, "Width": 150 },
				{ "DataProperty": "Evaluated", "Orderable":true, "Width": 150 }
			]
        }
	],
	"Forms":
	[
		{
			"Id": "Custom",
			"FormType": "Custom",
			"Tabs": 
			[
				{
					"Label": "Datos",
					"Rows": [
						{
							"Fields": [
								{ "Name": "LearningId", "ColSpan": 2 },
								{ "Name": "Signature" }
							]
						},
						{
							"Label": "Assistent",
							"Fields": [
								{ "Name": "Name" },
								{ "Name": "FirstName" },
								{ "Name": "NIF" }
							]
						},
						{
							"Fields": [
								{ "Name": "Phone" },
								{ "Name": "Birthday" },
								{ "Name": "Gender" }
							]
						},
						{
							"Fields": [
								{ "Name": "Email", "ColSpan": 3 }
							]
						},
						{
							"Label": "Tutor",
							"Fields": [
								{ "Name": "TutorName", "Label": "Nom" },
								{ "Name": "TutorFirstName", "Label": "Cognoms", "ColSpan": 2 }
							]
						},
						{
							"Fields": [
								{ "Name": "TutorNIF", "Label": "NIF" },
								{ "Name": "TutorPhone", "Label": "Telèfon"},
								{ "Type": "Blank" }
							]
						},
						{
							"Fields": [
								{ "Name": "Address" },
								{ "Name": "LocationPostalCodeId", "Label": "C.P."}
							]
						},
						{
							"Label": "Observacions",
							"Fields": [
								{ "Name": "LOPD", "Label": "La imatge pot aparèixer en fotografies corresponents publicacions a les xarxes socials i web de Viu Lleure" },
								{ "Name": "RRSS", "Label": "Que s'incloguin les dades de contacte als següents canals informatius" }
							]
						},
						{
							"Fields": [
								{ "Name": "Special", "ColSpan": 3 }
							]
						},
						{
							"Fields": [
								{ "Name": "Conocio", "ColSpan": 3 }
							]
						}
					]
				},
				{
					"Label": "Documentació",
					"Rows": [
						{
							"Fields": [
								{ "Name": "DNI1", "Config": "LVU" },
								{ "Name": "DNI2", "Config": "LVU" },
								{ "Name": "TS","Config": "LVU" }
							]
						}
					]
				}
			]
		}
	]
},
	{
    "Id": 202,
    "ItemName": "LearningCancelation",
    "Layout": {
        "Icon": "fa fa-ban",
        "Label": "Cancelació",
        "LabelPlural": "Cancelacións",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "LearningId" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [ { "ItemName":"Learning" }, { "ItemName": "Core_User" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "LearningId", "Label": "Curs", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
		{ "Name": "Core_UserId", "Label": "Usuari", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
		{ "Name": "Date", "Label": "Data", "Type": "datetime", "Required": true },
		{ "Name": "Reason", "Label": "Motiu", "Type": "textarea", "Required": true, "Length": 500 }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 2,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true }
            ]
        }
	]
},
	{
    "Id": 203,
    "ItemName": "LearningSeasson",
    "Layout": {
        "Icon": "fa fa-chalkboard-teacher",
        "Label": "Sessió",
        "LabelPlural": "Sessions",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "LearningId" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [ { "ItemName":"Learning" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "LearningId", "Label": "Curs", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
		{ "Name": "Date", "Label": "Data", "Type": "datetime", "Required": true },
		{ "Name": "TimeStart", "Label": "Inici", "Type": "int", "Required": true },
		{ "Name": "TimeEnd", "Label": "Fi", "Type": "int", "Required": true }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 2,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true }
            ]
        },
        {
			"Id": "ByLearning",
			"FormId": "Custom",
			"Layout": 1,
            "EditAction": 2,
			"Title": "Calendari",
			"Parameters": [ {"Name": "LearningId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "Date", "Orderable":true },
				{ "DataProperty": "TimeStart" },
				{ "DataProperty": "TimeEnd" }
			]
        }
	]
},
	{
    "Id": 201,
    "ItemName": "LearningStatus",
    "Layout": {
        "Icon": "fa fa-tasks-alt",
        "Label": "Estat de la formació",
        "LabelPlural": "Estats de la formació",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nombre", "Type": "text", "Length": 50, "Required": true }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 2,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true }
            ]
        }
	]
},
	{
    "Id": 206,
    "ItemName": "LearningTeacher",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-user-graduate",
        "Label": "Formador",
        "LabelPlural": "Formadors",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"NeedFK": [ "Learning" ],
    "ForeignValues": [ { "ItemName": "Core_User" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Length": 200, "Required": true },
        { "Name": "NIF", "Label": "NIF", "Type": "text", "Length": 10, "Required": true },
        { "Name": "Externo", "Label": "Extern", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Email", "Label": "Email", "Type": "email" },
        { "Name": "Phone", "Label": "Telèfon", "Type": "text", "Length": 15 },
		{ "Name": "Address", "Label": "Adreça", "Type": "text", "Length": 100, "Required": true },
		{ "Name": "LocationPostalCodeId", "Label": "C.P. Localitat", "Type": "Long", "Required": true },
		{ "Name": "LOPD", "Label": "LOPD", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "Core_UserId", "Label": "Usuari", "Type": "applicationUser" },
		{ "Name": "CertificacioAntecedentes", "Label": "Certificat antecedents", "Type": "DocumentFile" }		
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 3,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true },
                { "DataProperty": "Email", "Search": true, "Width": 250 },
                { "DataProperty": "Phone", "Search": true, "Width": 120 },
                { "DataProperty": "Externo", "Search": true, "Width": 80 }
            ]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
				{
					"Persistent": true,
					"Rows": [
						{
							"Fields": [
								{ "Name": "Name", "ColSpan": 2 },
								{ "Name": "NIF" },
								{ "Name": "Externo" }
							]
						}
					]
				},
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
                            "Fields": [
                                { "Name": "Email", "ColSpan": 2 },
								{ "Name": "Phone" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Address", "ColSpan": 2 },
								{ "Name": "LocationPostalCodeId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "CertificacioAntecedentes" },
                                { "Name": "LOPD" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 207,
    "ItemName": "LearningTeacherAssignation",
    "Description": "Formadors dels cursos",
    "Layout": {
        "Icon": "fa fa-list",
        "Label": "Formador",
        "LabelPlural": "Formadors",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "AlumnoId" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [
        { "ItemName": "Learning" },
        { "ItemName": "LearningTeacher" }
    ],
    "PrimaryKeys": [ ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "LearningId", "Label": "Curs", "Type": "long", "Required": true, "ColumnDataType": "text" },
        { "Name": "LearningTeacherId", "Label": "Formador", "Type": "long", "Required": true, "ColumnDataType": "text" }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Exportable": true,
			"Columns": [
				{ "DataProperty": "LearningId" },
				{ "DataProperty": "LearningTeacherId" }
          ]
        },
        {
			"Id": "ByLearning",
            "FormId": "Custom",
            "Layout": 1,
			"EditAction": 9,
			"ForceHeight":  300,
			"ItemLink": "LearningTeacher",
            "Parameters": [ {"Name": "LearningId", "Value": "#actualItemId#"}, {"Name": "Active", "Value": "1"} ],
            "Columns": [
                { "DataProperty": "LearningTeacherId", "Linkable": true }
            ]
        },
        {
			"Id": "ByLearningTeacher",
            "FormId": "Custom",
            "Layout": 1,
			"EditAction": 9,
			"ForceHeight":  300,
			"ItemLink": "Learning",
            "Parameters": [ {"Name": "LearningTeacherId", "Value": "#actualItemId#"}, {"Name": "Active", "Value": "1"} ],
            "Columns": [
                { "DataProperty": "LearningId", "Linkable": true }
            ]
        }
    ]
},
	{
    "Id": 9932,
    "ItemName": "Licitacion",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Licitació",
        "LabelPlural": "Licitacions",
        "Description": {
            "Pattern": "{0} - {1}",
            "Fields": [
				{ "Name": "ClienteId" },
                { "Name": "Referencia" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [  {"ItemName":"Cliente"} ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "ClienteId", "Label": "Client", "Type": "long", "Required": true, "ColumnDataType": "Text", "FK": true },
        { "Name": "Referencia", "Label": "Referència", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripció", "Type": "textarea", "Length": 2000 },
        { "Name": "Url", "Label": "Url", "Type": "Url" }
    ],
    "Lists": [
        {
          "Id": "Custom",
          "FormId": "Custom",
          "Layout": 1,
          "Exportable": false,
          "EditAction": 4,
		  "ForceHeight": 250,
          "Columns": [
            { "DataProperty": "ClienteId", "Orderable":true, "Search": true },
            { "DataProperty": "Referencia", "Orderable":true, "Search": true, "Width": 350 },
            { "DataProperty": "Descripcion", "Orderable":true, "Search": true, "Width": 350 }
          ]
        },
        {
			"Id": "ByCliente",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 2,
			"PageSize": 50,
			"ItemLink": "Licitacion",
			"Parameters": [ {"Name": "ClienteId", "Value": "#actualItemId#"} ],
			"Columns": [
				{ "DataProperty": "Referencia", "Orderable":true, "Search": true, "Width": 350 },
				{ "DataProperty": "Descripcion", "Orderable":true }
			]
        }
    ]
},
	{
    "Id": 101,
    "ItemName": "Monitor",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-user-graduate",
        "Label": "Monitor",
        "LabelPlural": "Monitors",
        "Description": {
            "Pattern": "{1}, {0}",
            "Fields": [
                { "Name": "FirstName" },
                { "Name": "LastName" }
            ]
        },
        "EditionType": "inline"
    },
    "ForeignValues": [ { "ItemName": "Core_User" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "FirstName", "Label": "Nom", "Type": "text", "Length": 20, "Required": true },
        { "Name": "LastName", "Label": "Cognoms", "Type": "text", "Length": 50, "Required": true },
        { "Name": "NIF", "Label": "NIF", "Type": "text", "Length": 10, "Required": true },
        { "Name": "Practicas", "Label": "En pràctiques", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" }, "FK": true },
        { "Name": "Email", "Label": "Email", "Type": "email" },
        { "Name": "Phone", "Label": "Telèfon", "Type": "text", "Length": 15 },
		{ "Name": "Address", "Label": "Adreça", "Type": "text", "Length": 100, "Required": true },
		{ "Name": "LOPD", "Label": "LOPD", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "Core_UserId", "Label": "Usuari", "Type": "applicationUser" },
		{ "Name": "CertificacioAntecedentes", "Label": "Certificat antecedents", "Type": "DocumentFile" },
		{ "Name": "DNI", "Label": "DNI", "Type": "DocumentFile" }		,
		{ "Name": "TituloMonitor", "Label": "Titol monitor", "Type": "DocumentFile" }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 3,
            "Columns": [
                { "DataProperty": "FirstName", "Search": true, "Orderable": true, "Linkable": true, "RenderData": "MONITOR_NombreCompleto" },
                { "DataProperty": "Email", "Search": true, "Width": 250 },
                { "DataProperty": "Phone", "Search": true, "Width": 120 },
                { "DataProperty": "Practicas", "Label": "Pràctiques", "Search": true, "Width": 90 },
                { "DataProperty": "LastName", "HiddenList": true }
            ]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
				{
					"Persistent": true,
					"Rows": [
						{
							"Fields": [
								{ "Name": "FirstName" },
								{ "Name": "LastName", "ColSpan": 2 },
								{ "Name": "NIF" }
							]
						}
					]
				},
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
                            "Fields": [
                                { "Name": "Email", "ColSpan": 2 },
								{ "Name": "Phone" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Address" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "CertificacioAntecedentes" },
                                { "Name": "DNI" },
                                { "Name": "TituloMonitor" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Practicas" },
                                { "Name": "LOPD" }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 302,
    "ItemName": "Noticia",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Notícia",
        "LabelPlural": "Notícies",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripción", "Type": "textarea", "Length": 1000 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
        { "Name": "Photo", "Label": "Imagen", "Type": "ImageFile" },
        { "Name": "Url", "Label": "Url", "Type": "Url" },
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" },
								{ "Name": "Weight" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Url" },
								{ "Name": "Photo" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Descripcion", "Wysiwyg": true }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 390,
    "ItemName": "Participante",
	"Features": {"Attachs": true},
    "Layout": {
        "Icon": "fa fa-user",
        "Label": "Assitent",
        "LabelPlural": "Assistentes",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
	"NeedFK": [ "Learning" ],
    "ForeignValues": [ { "ItemName": "Core_User" } ],
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nom", "Type": "text", "Length": 200, "Required": true },
        { "Name": "NIF", "Label": "NIF", "Type": "text", "Length": 10, "Required": true },
        { "Name": "Email", "Label": "Email", "Type": "email" },
        { "Name": "Phone", "Label": "Telèfon", "Type": "text", "Length": 15 },
		{ "Name": "Address", "Label": "Adreça", "Type": "text", "Length": 100, "Required": true },
		{ "Name": "LocationPostalCodeId", "Label": "C.P. Localitat", "Type": "Long", "Required": true },
		{ "Name": "LOPD", "Label": "LOPD", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" } },
		{ "Name": "TutorName", "Label": "Tutor", "Type": "text", "Length": 200, "Required": true },
        { "Name": "TutorNIF", "Label": "NIF", "Type": "text", "Length": 10, "Required": true },
        { "Name": "TutorEmail", "Label": "Email", "Type": "email" },
        { "Name": "TutorPhone", "Label": "Telèfon", "Type": "text", "Length": 15 },
		{ "Name": "ResponsabilidadCovid", "Label": "Responsabilidad Covid", "Type": "DocumentFile" }		
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 3,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true },
                { "DataProperty": "Email", "Search": true, "Width": 250 },
                { "DataProperty": "Phone", "Search": true, "Width": 120 },
                { "DataProperty": "TutorName", "Search": true, "Width": 120 }
            ]
        }
	],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
				{
					"Persistent": true,
					"Rows": [
						{
							"Fields": [
								{ "Name": "Name", "ColSpan": 2 },
								{ "Name": "NIF" }
							]
						}
					]
				},
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
                        {
                            "Fields": [
                                { "Name": "Email", "ColSpan": 2 },
								{ "Name": "Phone" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "Address", "ColSpan": 2 },
								{ "Name": "LocationPostalCodeId" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "ResponsabilidadCovid" },
                                { "Name": "LOPD" }
                            ]
                        },
                        {
							"Label": "Tutor",
                            "Fields": [
                                { "Name": "TutorName", "ColSpan": 2 },
                                { "Name": "TutorNIF" }
                            ]
                        },
                        {
                            "Fields": [
                                { "Name": "TutorEmail", "ColSpan": 2 },
                                { "Name": "TutorPhone" }
                            ]
                        }
					]
				},
                {
                    "Label": "Inscripcions",
                    "Id": "Data",
                    "Rows": [
                        {
                            
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 301,
    "ItemName": "TextoWeb",
    "Layout": {
        "Icon": "fa fa-cog",
        "Label": "Text web",
        "LabelPlural": "Textos web",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
				{ "Name": "Title" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Title", "Label": "Titòl", "Type": "text", "Required": true, "Length": 100 },
        { "Name": "Descripcion", "Label": "Descripción", "Type": "textarea", "Length": 200 },
        { "Name": "Published", "Label": "Publicat", "Type": "boolean", "DataFormat": { "Name": "ToBooleanCheck" }},
        { "Name": "Weight", "Label": "Pes", "Type": "int", "Required": true }
    ],
    "Lists": [
        {
			"Id": "Custom",
			"FormId": "Custom",
			"Layout": 1,
			"EditAction": 3,
			"Columns": [
				{ "DataProperty": "Title", "Orderable":true, "Search": true, "Linkable": true },
				{ "DataProperty": "Weight", "Orderable":true, "Width": 90 },
				{ "DataProperty": "Published", "Orderable":true, "Width": 90 }
			]
        }
    ],
	"Forms": [ 
		{
            "Id": "Custom",
            "FormType": "Custom",
            "DefaultSelected": true,
            "Tabs": [
                {
                    "Label": "Datos",
                    "Id": "Data",
                    "Rows": [
						{
							"Fields": [
								{ "Name": "Title", "ColSpan": 2 },
								{ "Name": "Published" },
								{ "Name": "Weight" }
							]
						},
                        {
                            "Fields": [
                                { "Name": "Descripcion", "Wysiwyg": true }
                            ]
                        }
					]
				}
            ]
        }
	]
},
	{
    "Id": 310,
    "ItemName": "TipoActividad",
    "Layout": {
        "Label": "Tipus d'actividad",
        "LabelPlural": "Tipus 'activitats",
        "Description": {
            "Pattern": "{0}",
            "Fields": [
                { "Name": "Name" }
            ]
        },
        "EditionType": "inline"
    },
    "Fields": [
        { "Name": "Id", "Type": "long", "Required": true },
        { "Name": "Name", "Label": "Nombre", "Type": "text", "Length": 50, "Required": true }
    ],
	"Lists": [
        {
            "Id": "Custom",
            "FormId": "Custom",
            "Layout": 1,
            "EditAction": 2,
            "Columns": [
                { "DataProperty": "Name", "Search": true, "Orderable": true, "Linkable": true }
            ]
        }
	]
}];